repos:
  - repo: local
    hooks:
      - id: helm-readme-generator
        name: Generate Helm README
        entry: |
          bash -c '
          set -e
          
          # Colors for output
          RED="\033[0;31m"
          GREEN="\033[0;32m"
          YELLOW="\033[1;33m"
          NC="\033[0m"
          
          # Function to print colored output
          print_status() {
              echo -e "${GREEN}[INFO]${NC} $1"
          }
          
          print_warning() {
              echo -e "${YELLOW}[WARNING]${NC} $1"
          }
          
          print_error() {
              echo -e "${RED}[ERROR]${NC} $1"
          }
          
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
              print_error "Docker is not installed. Please install Docker to use this pre-commit hook."
              exit 1
          fi
          
          # Check if Docker daemon is running
          if ! docker info &> /dev/null; then
              print_error "Docker daemon is not running. Please start Docker and try again."
              exit 1
          fi
          
          # Docker image to use
          IMAGE_NAME="helm-readme-generator"
          CHART_DIR="chart"
          README_FILE="$CHART_DIR/README.md"
          
          print_status "Checking if $IMAGE_NAME image is available locally..."
          
          # Check if image exists locally, if not pull it
          if ! docker image inspect "$IMAGE_NAME" &> /dev/null; then
              print_warning "Image $IMAGE_NAME not found locally. Pulling..."
              if ! docker pull "$IMAGE_NAME"; then
                  print_error "Failed to pull $IMAGE_NAME image. Please check your internet connection and try again."
                  exit 1
              fi
          fi
          
          print_status "Generating Helm README..."
          
          # Run the helm-readme-generator
          if docker run --rm \
              -v "$(pwd)/$CHART_DIR:/my_helm" \
              -w /my_helm \
              "$IMAGE_NAME" \
              readme-generator \
              --readme README.md \
              --values values.yaml; then
              
              print_status "README.md generated successfully!"
              
              # Check if README.md was actually modified
              if git diff --quiet "$README_FILE"; then
                  print_status "README.md is up to date."
              else
                  print_warning "README.md has been updated. Please review the changes and commit them."
                  print_status "You can run \"git diff $README_FILE\" to see the changes."
              fi
          else
              print_error "Failed to generate README.md. Please check the error messages above."
              exit 1
          fi
          '
        language: system
        files: ^chart/(values\.yaml|README\.md)$
        pass_filenames: false 