## @section Carto database parameters

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
## @param postgresql.existingSecret Name of an existing secret containing the PostgreSQL password ('postgresql-password' key)
##
postgresql:
  enabled: true
  ## Bitnami Postgresql image version
  ## ref: https://hub.docker.com/r/bitnami/postgresql/tags
  ## @param scheduler.image.registry Postgrrsql image registry
  ## @param scheduler.image.repository Postgresql image repository
  ## @param scheduler.image.tag Postgresql image tag (immutable tags are recommended)
  ## @param scheduler.image.pullPolicy Postgresql image pull policy
  ## @param scheduler.image.pullSecrets Postgresql image pull secrets
  ## @param scheduler.image.debug Enable image debug mode
  ##
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 13.2.0-debian-10-r88
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
    ## Set to true if you would like to see extra information on logs
    ## It turns BASH and/or NAMI debugging in the image
    ##
    debug: false
  ## This secret is used in case of postgresql.enabled=true and we would like to specify password for newly created postgresql instance
  ##
  postgresqlUsername: postgres
  postgresqlPassword:
  existingSecret: ""
  fullnameOverride: workspace-postgres
  primary:
    sidecars:
    - name: workspace-migrations
      image: gcr.io/carto-onprem-artifacts/workspace-db:2021.12.14.02
      imagePullPolicy: Always
      command: [ "/bin/sh", "-c", "/usr/src/app/onprem-init-db.sh && while true; do echo $(date -u);sleep 1;done" ]
      env:
      - name: POSTGRES_ADMIN_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value:
      - name: WORKSPACE_POSTGRES_USER
        value: workspace_admin
      - name: WORKSPACE_POSTGRES_PASSWORD
        value:
      - name: WORKSPACE_POSTGRES_HOST
        value: localhost
      - name: WORKSPACE_POSTGRES_DB
        value: workspace
      - name: WORKSPACE_POSTGRES_PORT
        value: "5432"

## Redis chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
## @param redis.enabled Switch to enable or disable the Redis&trade; helm
## @param redis.auth.enabled Switch to enable or disable authentication
## @param redis.auth.password Redis&trade; password
## @param redis.auth.existingSecret Name of existing secret object containing the password
## @param redis.architecture Cluster settings
##
redis:
  enabled: true
  auth:
    enabled: false
    ## Redis password (both master and slave). Defaults to a random 10-character alphanumeric string if not set and auth.enabled is true.
    ## The password value is ignored if existingSecret is set
    password: ""
    existingSecret: ""
  architecture: standalone
