{{- if .Values.gateway.enabled }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ template "carto.gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.gateway.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.gateway.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: {{ .Values.gateway.listeners.https.name }}
    protocol: HTTPS
    port: {{ .Values.gateway.listeners.https.port }}
    tls:
      mode: {{ .Values.gateway.tls.mode }}
      {{- if .Values.gateway.tlsCertificates.customSSLCerts.enabled }}
      certificateRefs:
      - kind: Secret
        name: {{ include "carto.gateway.tlsCertificates.customSSLCerts.secretName" . }}
      {{- else if .Values.gateway.tlsCertificates.managedCerts.enabled }}
      options:
        networking.gke.io/pre-shared-certs: {{ .Values.gateway.tlsCertificates.managedCerts.name }}
      {{- end }}
  - name: {{ .Values.gateway.listeners.http.name }}
    port: {{ .Values.gateway.listeners.http.port }}
    protocol: HTTP
  {{- if .Values.gateway.staticIP.enabled }}
  addresses:
  - type: {{ .Values.gateway.address.type }}
    value: {{ .Values.gateway.staticIP.value }}
  {{- end }}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ template "carto.gateway.fullname" . }}-https
  namespace: {{ .Release.Namespace | quote }}
  labels:
    gateway: {{ template "carto.gateway.fullname" . }}
spec:
  parentRefs:
  - name: {{ template "carto.gateway.fullname" . }}
    sectionName: {{ .Values.gateway.listeners.https.name }}
  hostnames:
  - {{ .Values.appConfigValues.selfHostedDomain | quote }}
  rules:
  - matches:
    - path:
        value: {{ .Values.gateway.path }}
    backendRefs:
    - name: {{ template "carto.router.fullname" . }}
      {{- if .Values.router.httpsEnabled }}
      port: {{ .Values.router.service.ports.https }}
      {{- else }}
      port: {{ .Values.router.service.ports.http }}
      {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ template "carto.gateway.fullname" . }}-http-to-https
  namespace: {{ .Release.Namespace | quote }}
spec:
  parentRefs:
  - name: {{ template "carto.gateway.fullname" . }}
    sectionName: {{ .Values.gateway.listeners.http.name }}
  hostnames:
  - {{ .Values.appConfigValues.selfHostedDomain | quote }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
