{{- if .Values.gateway.enabled }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ template "carto.gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      {{ if .Values.gateway.tlsCertificates.customCerts.enabled }}
      certificateRefs:
      - kind: Secret
        name: {{ include "carto.gateway.tlsCertificates.secretName" . }}
      {{- else if and .Values.gateway.tlsCertificates.managedCerts.enabled (eq .Values.replicated.platformDistribution "gke") }}
      options:
        networking.gke.io/pre-shared-certs: {{ .Values.gateway.tlsCertificates.managedCerts.name }}
      {{- end }}
  - name: http
    port: 80
    protocol: HTTP
  {{ if .Values.gateway.staticIP.enabled }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.staticIP.value }}
  {{- end }}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ template "carto.gateway.fullname" . }}-https
  namespace: {{ .Release.Namespace | quote }}
  labels:
    gateway: {{ template "carto.gateway.fullname" . }}
spec:
  parentRefs:
  - name: {{ template "carto.gateway.fullname" . }}
    sectionName: https
  hostnames:
  - {{ .Values.appConfigValues.selfHostedDomain | quote }}
  rules:
  - matches:
    - path:
        value: {{ .Values.gateway.path }}
    backendRefs:
    - name: {{ template "carto.router.fullname" . }}
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ template "carto.gateway.fullname" . }}-http-to-https
  namespace: {{ .Release.Namespace | quote }}
spec:
  parentRefs:
  - name: {{ template "carto.gateway.fullname" . }}
    sectionName: http
  hostnames:
  - {{ .Values.appConfigValues.selfHostedDomain | quote }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
