{{- if and .Values.gateway.enabled (eq .Values.replicated.platformDistribution "gke") }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ template "carto.gateway.fullname" . }}-healthcheck
  namespace: {{ .Release.Namespace | quote }}
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTPS
      httpsHealthCheck:
        port: {{ .Values.router.service.ports.https }}
        portName: https
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: {{ template "carto.router.fullname" . }}
{{- end }}
