{{- if .Values.notifier.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "carto.notifier.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: notifier
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: notifier
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" . | nindent 14 }}
              app.kubernetes.io/component: router
      ports:
        - port: {{ .Values.notifier.containerPorts.http }}
          protocol: TCP
    - from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" . | nindent 14 }}
              app.kubernetes.io/component: workspace-subscriber
      ports:
        - port: {{ .Values.notifier.containerPorts.internal }}
          protocol: TCP
{{- end }}
