chart-dirs:
  - chart
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
check-version-increment: true
debug: true
remote: origin
target-branch: stable
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true