{{- if not .Values.router.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.router.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: router
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  # Common configuration
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonConfiguration "context" $ ) | nindent 2 }}
  # router configuration
  {{- include "common.tplvalues.render" ( dict "value" .Values.router.configuration "context" $ ) | nindent 2 }}
