{{- if .Values.router.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "carto.router.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.router.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.router.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.router.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.router.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.appConfigValues.selfHostedDomain }}
    - host: {{ .Values.appConfigValues.selfHostedDomain }}
      http:
        paths:
          - path: {{ .Values.router.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.router.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "carto.router.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
          {{- if .Values.router.ingress.extraPaths }}
          {{- toYaml .Values.router.ingress.extraPaths | nindent 10 }}
          {{- end }}
    {{- end }}
    {{- range (coalesce .Values.router.ingress.extraHosts .Values.router.ingress.hosts) }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "carto.router.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
    {{- if .Values.router.ingress.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.router.ingress.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.router.ingress.tls .Values.router.ingress.extraTls }}
  tls:
     {{- if .Values.router.ingress.tls }}
    - hosts:
        - {{ .Values.appConfigValues.selfHostedDomain | quote }}
      secretName: {{ .Values.tlsCerts.existingSecret.name }}
    {{- end }}
    {{- if .Values.router.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.router.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
