{{- if and .Values.router.podDisruptionBudget.enabled}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "carto.router.fullname" . }}-pdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
spec:
{{- if .Values.router.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.router.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.router.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.router.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "carto.router.fullname" . }}
{{- end }}