{{- if not .Values.router.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.router.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: router
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  .secret.env: |
    # Common configuration
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonSecretConfiguration "context" $ ) | nindent 4 }}
    # router configuration
    {{- include "common.tplvalues.render" ( dict "value" .Values.router.secretConfiguration "context" $ ) | nindent 4 }}
{{- end }}
