{{- if and .Values.tlsCerts.customCertsEnabled .Values.replicated.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carto.tlsCerts.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{ template "carto.tlsCerts.secretCertKey" . }}: {{ .Values.tlsCerts.customCertificateValue | nindent 4 }}
  {{ template "carto.tlsCerts.secretKeyKey" . }}: {{ .Values.tlsCerts.customPrivateKeyValue | nindent 4 }}
{{- end }}
