{{- if and (not .Values.internalRedis.enabled) (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carto.redis.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
      {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.appConfigValues.b64EncodeSecrets }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- else }}
  redis-password: {{ .Values.externalRedis.password | quote }}
{{- end }}
{{- end }}
