{{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carto.postgresql.configMapName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ include "carto.postgresql.configMapMountFilename" . }}: {{ .Values.externalPostgresql.sslCA | quote }}
{{- end }}
