{{- if or .Values.customCA .Values.externalProxy.sslCA }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carto.customCA.configMapName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ include "carto.customCA.configMapMountFilename" . }}: {{ include "carto.customCA.bundle" . | quote }}
{{- end }}
