{{- if not .Values.google.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.google.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-www
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  {{ template "carto.google.secretKey" . }}: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.google.credentialFile "context" $ ) | nindent 4 }}
{{- end }}
