{{- if not .Values.cartoSecrets.defaultGoogleServiceAccount.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.google.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.appConfigValues.b64EncodeSecrets }}
  key.json: {{ .Values.cartoSecrets.defaultGoogleServiceAccount.value | b64enc | quote }}
{{- else }}
  key.json: {{ .Values.cartoSecrets.defaultGoogleServiceAccount.value | quote }}
{{- end }}
{{- end }}
