{{- if and .Values.router.ingress.enabled .Values.replicated.enabled (eq .Values.replicated.platformDistribution "gke") }}
# BackendConfig object is used to configure Ingress features related to the
## backends
## CARTO needs to extend the timeout of the connections to 600 seconds
## https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#timeout
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: carto-service-backend-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carto
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  timeoutSec: 600
---
## FrontendConfig object is used to configure downstream Ingress features
## Redirect port 80 to 443 automatically
## https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: carto-ingress-frontend-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carto
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  ## To attach a SSL Policy uncomment the line below
  # sslPolicy: my-ssl-policy
{{- end }}
