{{- if .Values.replicated.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: support-bundle
  name: {{ .Release.Name }}-support-bundle
  namespace: {{ .Release.Namespace | quote }}
stringData:
    # To use it: kubectl support-bundle --load-cluster-specs --selector=carto.com/kind=support-bundle
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: {{ .Release.Name }}-support-bundle
      namespace: {{ .Release.Namespace | quote }}
    spec:
      collectors:
    {{- include "carto.replicated.commonChecks.collectors" . | nindent 6 }}
        - clusterInfo: {}
        - clusterResources:
            namespaces:
                - {{ .Release.Namespace }}
        - logs:
            collectorName: namespace-{{ .Release.Namespace }}-logs
            name: namespace-{{ .Release.Namespace }}-logs
            namespace: {{ .Release.Namespace }}
            limits:
              maxAge: 720h # 30*24
              maxLines: 10000
              maxBytes: 5000000
        - runPod:
            collectorName: support-run-health-on-maps-api
            name: support-run-health-on-maps-api
            namespace: {{ .Release.Namespace | quote }}
            timeout: 30s   # Maximum supported 30s !
            podSpec:
              containers:
                - name: run-health
                  image: {{ template "carto.mapsApi.image" . }}
                  imagePullPolicy: Always
                  command: ["bash"]
                  args: ["-exc", "npm run ready-to-run:built"]
                  env:
                    - name: WORKSPACE_POSTGRES_PASSWORD
                      value: {{ .Values.externalPostgresql.password | quote }}
                      # valueFrom:
                      #   secretKeyRef:
                      #     name: {{ include "carto.postgresql.secretName" . }}
                      #     key: {{ include "carto.postgresql.secret.key" . }}
                    - name: REDIS_PASSWORD
                      {{- if .Values.internalRedis }}
                      value: {{ .Values.internalRedis.auth.password | quote }}
                      {{- end }}
                      {{- if not .Values.internalRedis }}
                      value: {{ .Values.externalRedis.password | quote }}
                      {{- end }}
                      # valueFrom:
                      #   secretKeyRef:
                      #     name: {{ include "carto.redis.secretName" . }}
                      #     key: {{ include "carto.redis.existingsecret.key" . | quote }}
                    - name: WORKSPACE_POSTGRES_HOST
                      value: {{ include "carto.postgresql.host" . }}
                    - name: WORKSPACE_POSTGRES_PORT
                      value: {{ include "carto.postgresql.port" . }}
                    - name: WORKSPACE_POSTGRES_DB
                      value: {{ include "carto.postgresql.databaseName" . }}
                    - name: WORKSPACE_POSTGRES_USER
                      value: {{ include "carto.postgresql.user" . }}
                    - name: MAPS_API_V3_TENANT_ID
                      value: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
                    - name: CARTO_SELFHOSTED_VERSION
                      value: {{ .Chart.AppVersion | quote }}
                    - name: REDIS_CACHE_PREFIX
                      value: "onprem"
                    - name: REDIS_HOST
                      value: {{ include "carto.redis.host" . }}
                    - name: AUTH0_DOMAIN
                      value: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
                    - name: AUTH0_AUDIENCE
                      value: "carto-cloud-native-api"
                    - name: MAPS_API_V3_JWT_SECRET
                      value: "dummy_placeholder_"
                    - name: PUBSUB_PROJECT_ID
                      value: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
                    - name: MAPS_API_V3_PUBSUB_TENANT_BUS_TOPIC
                      value: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/topics/tenant-bus"
      analyzers:
    {{- include "carto.replicated.commonChecks.analyzers" . | nindent 6 }}
        - textAnalyze:
            checkName: Required check maps-api could run
            fileName: support-run-health-on-maps-api/support-run-health-on-maps-api.log
            regex: "overall_status: 'up'"
            outcomes:
              - pass:
                  when: "true"
                  message: "No error found"
              - fail:
                  when: "false"
                  message: "We found some kind of error during the execution"
        - yamlCompare:
            annotations:
              kots.io/installer: "true"
            checkName: Kubernetes Installer
            outcomes:
              - fail:
                  message: The Kubernetes installer for this version differs from what you have installed. It is recommended that you run the updated Kubernetes installer before deploying this version.
                  uri: https://kurl.sh/carto
              - pass:
                  message: The Kubernetes installer for this version matches what is currently installed.
        - clusterPodStatuses:
            name: unhealthy
            namespaces:
                - {{ .Release.Namespace }}
            outcomes:
            - fail:
                when: "== CrashLoopBackOff"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in a CrashLoopBackOff state.
            - fail:
                when: "== ImagePullBackOff"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in a ImagePullBackOff state.
            - fail:
                when: "== Pending"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in a Pending state.
            - fail:
                when: "== Evicted"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in a Evicted state.
            - fail:
                when: "== Terminating"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in a Terminating state.
            - fail:
                when: "== Init:Error"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in an Init:Error state.
            - fail:
                when: "== Init:CrashLoopBackOff"
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is in an Init:CrashLoopBackOff state.
            - fail:
                when: "!= Healthy" # Catch all unhealthy pods. A pod is considered healthy if it has a status of Completed, or Running and all of its containers are ready.
                # {{ printf "{{ .Status.Reason }}" }} displays the current status of the pod, while {{ printf "{{ .Status.Message }}" }} provides a detailed explanation of why the pod is unhealthy, based on logged events.
                message: Pod {{ printf "{{ .Namespace }}" }}/{{ printf "{{ .Name }}" }} is unhealthy with a status of {{ printf "{{ .Status.Reason }}" }}. Message is {{ printf "{{ .Status.Message }}" }} 
{{- end }}