{{- if eq .Values.workloadIdentityConfig.enableWorkloadIdentity "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carto
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ .Chart.Name }}-workload-identity
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentityConfig.workloadIdentitySaEmail | quote }}
automountServiceAccountToken: {{ .Values.workspaceApi.serviceAccount.automountServiceAccountToken }}
{{- end }}
