{{- if not .Values.mapsApi.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.mapsApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: maps-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  CARTO_SELFHOSTED_DOMAIN: {{ .Values.cartoConfigValues.selfHostedDomain | quote }}
  CARTO_SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  CARTO_SELFHOSTED_NAME: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  DO_ENABLED: "false"
  LOG_LEVEL: "debug"
  MAPS_API_V3_PORT: "{{ .Values.mapsApi.containerPorts.http }}"
  MAPS_API_V3_RESOURCE_URL_ALLOWED_HOSTS: {{ .Values.cartoConfigValues.selfHostedDomain | quote }}
  MAPS_API_V3_RESOURCE_URL_HOST: {{ .Values.cartoConfigValues.selfHostedDomain | quote }}
  MAPS_API_V3_RESOURCE_URL_TEMPLATE_NEW: 'https://${host}/api/${path}'
  MAPS_API_V3_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  REDIS_CACHE_PREFIX: "onprem"
  REDIS_HOST: {{ include "carto.redis.host" . }}
  REDIS_PORT: {{ include "carto.redis.port" . }}
  SELFHOSTED_DOMAIN: {{ .Values.cartoConfigValues.selfHostedDomain | quote }}
  SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  SELFHOSTED_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  WORKSPACE_IMPORTS_BUCKET: {{ .Values.cartoConfigValues.workspaceImportsBucket | quote }}
  WORKSPACE_POSTGRES_DB: {{ include "carto.postgresql.databaseName" . }}
  WORKSPACE_POSTGRES_HOST: {{ include "carto.postgresql.host" . }}
  WORKSPACE_POSTGRES_PORT: {{ include "carto.postgresql.port" . }}
  WORKSPACE_POSTGRES_USER: {{ include "carto.postgresql.user" . }}
  WORKSPACE_PUBSUB_DATA_UPDATES_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/data-updates-workspace-sub"
  WORKSPACE_PUBSUB_DATA_UPDATES_TOPIC: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/topics/data-updates"
  WORKSPACE_THUMBNAILS_BUCKET: {{ .Values.cartoConfigValues.workspaceThumbnailsBucket | quote }}
{{- end }}