{{- if and (include "carto.baseUrl" .) (not .Values.cartoConfigValues.onlyRunRouter) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.mapsApi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: maps-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mapsApi.replicaCount }}
  {{- if .Values.mapsApi.updateStrategy }}
  strategy: {{- toYaml .Values.mapsApi.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: maps-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/maps-api/configmap.yaml") . | sha256sum }}
        checksum/feature-flags-config: {{ include (print $.Template.BasePath "/custom-feature-flags-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/maps-api/secret.yaml") . | sha256sum }}
        checksum/redis-password: {{ include "carto.redis.passwordChecksum" . }}
        checksum/postgresql-password: {{ include "carto.postgresql.passwordChecksum" . }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- if .Values.mapsApi.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: maps-api
        {{- if .Values.mapsApi.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.commonSA.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.mapsApi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mapsApi.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.mapsApi.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mapsApi.podAffinityPreset "component" "maps-api" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mapsApi.podAntiAffinityPreset "component" "maps-api" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.mapsApi.nodeAffinityPreset.type "key" .Values.mapsApi.nodeAffinityPreset.key "values" .Values.mapsApi.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.mapsApi.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.mapsApi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mapsApi.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.mapsApi.priorityClassName }}
      priorityClassName: {{ .Values.mapsApi.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.mapsApi.schedulerName }}
      schedulerName: {{ .Values.mapsApi.schedulerName | quote }}
      {{- end }}
      {{- if .Values.mapsApi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.mapsApi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.internalPostgresql.enabled }}
        {{ include "carto.postgresql-init-container" (dict "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.internalRedis.enabled }}
        {{ include "carto.redis-init-container" . | nindent 8 }}
        {{- end }}
        {{- if .Values.mapsApi.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.mapsApi.terminationGracePeriodSeconds }}
      containers:
        - name: maps-api
          image: {{ template "carto.mapsApi.image" . }}
          imagePullPolicy: {{ .Values.mapsApi.image.pullPolicy }}
          {{- if .Values.mapsApi.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.mapsApi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.mapsApi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.mapsApi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              npm run start:built
          {{- end }}
          env:
            - name: WORKSPACE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.key" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.redis.secretName" . }}
                  key: {{ include "carto.redis.existingsecret.key" . | quote }}
            {{- include "carto._utils.generateSecretDefs" (dict "vars" (list
             "CARTO_SELFHOSTED_INSTANCE_ID"
             "BIGQUERY_OAUTH2_CLIENT_SECRET"
             "ENCRYPTION_SECRET_KEY"
             "EXPORTS_S3_BUCKET_ACCESS_KEY_ID"
             "EXPORTS_S3_BUCKET_SECRET_ACCESS_KEY"
             "MAPS_API_V3_JWT_SECRET"
             "LAUNCHDARKLY_SDK_KEY"
             ) "context" $ ) | nindent 12 }}
            {{- if .Values.mapsApi.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "carto.mapsApi.configmapName" . }}
            {{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
             "CARTO_SELFHOSTED_INSTANCE_ID"
             "BIGQUERY_OAUTH2_CLIENT_SECRET"
             "ENCRYPTION_SECRET_KEY"
             "EXPORTS_S3_BUCKET_ACCESS_KEY_ID"
             "EXPORTS_S3_BUCKET_SECRET_ACCESS_KEY"
             "MAPS_API_V3_JWT_SECRET"
             "LAUNCHDARKLY_SDK_KEY"
             ) "context" $ ) -}}
            {{- if $secretContent }}
            - secretRef:
                name: {{ include "carto.mapsApi.secretName" . }}
            {{- end }}
            {{- if .Values.mapsApi.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.mapsApi.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.mapsApi.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.mapsApi.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.mapsApi.resources }}
          resources: {{- toYaml .Values.mapsApi.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.mapsApi.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.mapsApi.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.mapsApi.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.mapsApi.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.mapsApi.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.mapsApi.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.mapsApi.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.mapsApi.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.mapsApi.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.mapsApi.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.mapsApi.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gcp-default-service-account-key
              mountPath: {{ include "carto.google.secretMountDir" . }}
              readOnly: true
            {{- if ( include "carto.googleCloudStorageServiceAccountKey.used" . ) }}
            - name: gcp-buckets-service-account-key
              mountPath: {{ include "carto.googleCloudStorageServiceAccountKey.secretMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
            - name: postgresql-ssl-ca
              mountPath: {{ include "carto.postgresql.configMapMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
            - name: redis-tls-ca
              mountPath: {{ include "carto.redis.configMapMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalProxy.enabled (or .Values.externalProxy.sslCA .Values.externalProxy.sslCAConfigmapName) }}
            - name: proxy-ssl-ca
              mountPath: {{ include "carto.proxy.configMapMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if .Values.cartoConfigValues.featureFlagsOverrides }}
            - name: feature-flags
              mountPath: {{ include "carto.featureFlags.configMapMountDir" . }}
              subPath: custom-feature-flags.yaml
              readOnly: true
            {{- end }}
          {{- if .Values.mapsApi.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.mapsApi.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.mapsApi.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: gcp-default-service-account-key
          secret:
            secretName: {{ include "carto.google.secretName" . }}
            items:
              - key: {{ include "carto.google.secretKey" . }}
                path: {{ include "carto.google.secretMountFilename" . }}
        {{- if ( include "carto.googleCloudStorageServiceAccountKey.used" . ) }}
        - name: gcp-buckets-service-account-key
          secret:
            secretName: {{ include "carto.googleCloudStorageServiceAccountKey.secretName" . }}
            items:
              - key: {{ include "carto.googleCloudStorageServiceAccountKey.secretKey" . }}
                path: {{ include "carto.googleCloudStorageServiceAccountKey.secretMountFilename" . }}
        {{- end }}
        {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
        - name: postgresql-ssl-ca
          configMap:
            name: {{ include "carto.postgresql.configMapName" . }}
        {{- end }}
        {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
        - name: redis-tls-ca
          configMap:
            name: {{ include "carto.redis.configMapName" . }}
        {{- end }}
        {{- if and .Values.externalProxy.enabled (or .Values.externalProxy.sslCA .Values.externalProxy.sslCAConfigmapName) }}
        - name: proxy-ssl-ca
          configMap:
            name: {{ include "carto.proxy.configMapName" . }}
        {{- end }}
        {{- if .Values.cartoConfigValues.featureFlagsOverrides }}
        - name: feature-flags
          configMap:
            name: {{ template "carto.featureFlags.configMapName" . }}
            items:
              - key: custom-feature-flags.yaml
                path: custom-feature-flags.yaml
        {{- end }}
        {{- if .Values.mapsApi.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mapsApi.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
