{{- if and .Values.ingress.enabled .Values.ingress.tlsCertificates.customCerts.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carto.ingress.tlsCertificates.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tlsCertificates.customCerts.certificateValueBase64 | nindent 4 }}
  tls.key: {{ .Values.ingress.tlsCertificates.customCerts.privateKeyValueBase64 | nindent 4 }}
{{- end }}
