{{- if and .Values.ingress.managedCerts.enabled (eq .Values.replicated.platformDistribution "gke") }}
## In case you want to use Google Managed Certificate for Ingress you will
## need to deploy the ManagedCertified object
## https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#setting_up_a_google-managed_certificate
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: carto-ingress-managed-cert
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carto
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  domains:
    - {{ .Values.appConfigValues.selfHostedDomain }}
{{- end }}
