# Azure Blob storage provider.
appConfigValues:
  selfHostedDomain: carto.example.invalid
  storageProvider: azure-blob
  azureStorageAccount: exampleaccount
  workspaceImportsBucket: example-imports
  workspaceThumbnailsBucket: example-thumbnails
