router:
  service:
    type: LoadBalancer
    annotations:
      # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/
      # https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "605"
