{{- if not .Values.ldsApi.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.ldsApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: lds-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  AUTH0_AUDIENCE: "carto-cloud-native-api"
  AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  AUTH0_NAMESPACE: "http://app.carto.com"
  CARTO_SELFHOSTED_DOMAIN: {{ .Values.appConfigValues.selfHostedDomain | quote }}
  CARTO_SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  CARTO_SELFHOSTED_NAME: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  DO_ENABLED: "false"
  LDS_PORT: {{ .Values.ldsApi.containerPorts.http | quote }}
  LOG_LEVEL: "debug"
  REDIS_CACHE_PREFIX: "onprem"
  REDIS_HOST: {{ include "carto.redis.host" . }}
  REDIS_PORT: {{ include "carto.redis.port" . }}
  REDIS_TLS_ENABLED: {{ .Values.externalRedis.tlsEnabled | quote }}
  {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
  REDIS_TLS_CA: {{ include "carto.redis.configMapMountAbsolutePath" . }}
  {{- end }}
  SELFHOSTED_DOMAIN: {{ .Values.appConfigValues.selfHostedDomain | quote }}
  SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  SELFHOSTED_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  WORKSPACE_IMPORTS_BUCKET: {{ .Values.appConfigValues.workspaceImportsBucket | quote }}
  WORKSPACE_POSTGRES_DB: {{ include "carto.postgresql.databaseName" . }}
  WORKSPACE_POSTGRES_HOST: {{ include "carto.postgresql.host" . }}
  WORKSPACE_POSTGRES_PORT: {{ include "carto.postgresql.port" . }}
  WORKSPACE_POSTGRES_USER: {{ include "carto.postgresql.user" . }}
  WORKSPACE_POSTGRES_SSL_ENABLED: {{ .Values.externalPostgresql.sslEnabled | quote }}
  {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA  }}
  WORKSPACE_POSTGRES_SSL_CA: {{ include "carto.postgresql.configMapMountAbsolutePath" . }}
  {{- end }}
  WORKSPACE_PUBSUB_DATA_UPDATES_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/data-updates-workspace-sub"
  WORKSPACE_PUBSUB_DATA_UPDATES_TOPIC: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/topics/data-updates"
  WORKSPACE_THUMBNAILS_BUCKET: {{ .Values.appConfigValues.workspaceThumbnailsBucket | quote }}
  LDS_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
{{- end }}
