apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-ldsApi
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ldsApi
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: ldsApi
  replicas: {{ default 1 .Values.ldsApi.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: ldsApi
      {{- if .Values.ldsApi.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.podLabels "context" $) | nindent 8 }}
      {{- end }}
      annotations:
      {{- if .Values.ldsApi.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.ldsApi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.ldsApi.priorityClassName | quote }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "carto.serviceAccountName" . }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "component" "ldsApi" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "ldsApi" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.ldsApi.nodeSelector }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- else }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.ldsApi.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.initContainers "context" $) | trim | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | trim | nindent 8 }}
      {{- end }}
      containers:
        - name: carto-ldsApi
          image: {{ include "carto.ldsApiImage" . }}
          imagePullPolicy: {{ .Values.ldsApi.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.ldsApi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.ldsApi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.ldsApi.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "carto.configure.common"  . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.ldsApi.containerPort }}
