{{ $secretContentLdsApi := include "carto._utils.generateSecretObjects" (dict "keys" (list "ENCRYPTION_SECRET_KEY") "context" $ )}}
{{- if $secretContentLdsApi }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.ldsApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: lds-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ $secretContentLdsApi | nindent 2 }}
{{- end }}
