{{- if (include "carto.baseUrl" .) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.importApi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: import-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.importApi.replicaCount }}
  {{- if .Values.importApi.updateStrategy }}
  strategy: {{- toYaml .Values.importApi.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: import-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/import-api/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/import-api/secret.yaml") . | sha256sum }}
        {{- if .Values.importApi.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importApi.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: import-api
        {{- if .Values.importApi.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importApi.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.importApi.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.importApi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.importApi.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.importApi.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.importApi.podAffinityPreset "component" "import-api" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.importApi.podAntiAffinityPreset "component" "import-api" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.importApi.nodeAffinityPreset.type "key" .Values.importApi.nodeAffinityPreset.key "values" .Values.importApi.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.importApi.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.importApi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.importApi.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.importApi.priorityClassName }}
      priorityClassName: {{ .Values.importApi.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.importApi.schedulerName }}
      schedulerName: {{ .Values.importApi.schedulerName | quote }}
      {{- end }}
      {{- if .Values.importApi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.importApi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.internalPostgresql.enabled }}
        {{ include "carto.postgresql-init-container" (dict "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.internalRedis.enabled }}
        {{ include "carto.redis-init-container" . | nindent 8 }}
        {{- end }}
        {{- if .Values.importApi.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importApi.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: import-api
          image: {{ template "carto.importApi.image" . }}
          imagePullPolicy: {{ .Values.importApi.image.pullPolicy }}
          {{- if .Values.importApi.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.importApi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.importApi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.importApi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              npm run start:built
          {{- end }}
          env:
            - name: WORKSPACE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.key" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.redis.secretName" . }}
                  key: {{ include "carto.redis.existingsecret.key" . | quote }}
            {{- include "carto._utils.generateSecretDefs" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "IMPORT_ACCESSKEYID"
              "IMPORT_SECRETACCESSKEY"
              "IMPORT_STORAGE_ACCESSKEY"
            ) "context" $ ) | nindent 12 }}
            {{- if .Values.importApi.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.importApi.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if not .Values.importApi.existingConfigMap }}
            - configMapRef:
                name: {{ template "carto.importApi.fullname" . }}
            {{- end }}
            {{- if .Values.importApi.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.importApi.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.importApi.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.importApi.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "IMPORT_ACCESSKEYID"
              "IMPORT_SECRETACCESSKEY"
              "IMPORT_STORAGE_ACCESSKEY"
            ) "context" $ ) -}}
            {{- if $secretContent }}
            - secretRef:
                name: {{ include "carto.importApi.secretName" . }}
            {{- end }}
          {{- if .Values.importApi.resources }}
          resources: {{- toYaml .Values.importApi.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.importApi.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.importApi.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.importApi.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.importApi.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.importApi.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.importApi.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.importApi.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.importApi.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.importApi.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.importApi.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.importApi.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.importApi.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gcp-default-service-account-key
              mountPath: {{ include "carto.google.secretMountDir" . }}
              readOnly: true
            {{- if ( include "carto.gcpBucketsServiceAccountKey.used" . ) }}
            - name: gcp-buckets-service-account-key
              mountPath: {{ include "carto.gcpBucketsServiceAccountKey.secretMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
            - name: postgresql-ssl-ca
              mountPath: {{ include "carto.postgresql.configMapMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
            - name: redis-tls-ca
              mountPath: {{ include "carto.redis.configMapMountDir" . }}
              readOnly: true
            {{- end }}
          {{- if .Values.importApi.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.importApi.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.importApi.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.importApi.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: gcp-default-service-account-key
          secret:
            secretName: {{ include "carto.google.secretName" . }}
            items:
              - key: {{ include "carto.google.secretKey" . }}
                path: {{ include "carto.google.secretMountFilename" . }}
        {{- if ( include "carto.gcpBucketsServiceAccountKey.used" . ) }}
        - name: gcp-buckets-service-account-key
          secret:
            secretName: {{ include "carto.gcpBucketsServiceAccountKey.secretName" . }}
            items:
              - key: {{ include "carto.gcpBucketsServiceAccountKey.secretKey" . }}
                path: {{ include "carto.gcpBucketsServiceAccountKey.secretMountFilename" . }}
        {{- end }}
        {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
        - name: postgresql-ssl-ca
          configMap:
            name: {{ include "carto.postgresql.configMapName" . }}
        {{- end }}
        {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
        - name: redis-tls-ca
          configMap:
            name: {{ include "carto.redis.configMapName" . }}
        {{- end }}
        {{- if .Values.importApi.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importApi.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
