{{- if not .Values.importApi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.importApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: import-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  # Common configuration
  # CARTO self hosted sensitive information
  ENCRYPTION_SECRET_KEY: {{ .Values.cartoSecrets.encryptionSecretKey }}
  REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.cartoSecrets.googleMapsApiKey }}
  # S3 custom buckets
  {{- if .Values.cartoConfigValues.storageProvider == 's3'}}
  IMPORT_ACCESSKEYID: {{ .Values.cartoSecrets.awsAccessKeyId | quote }}
  IMPORT_SECRETACCESSKEY: {{ .Values.cartoSecrets.awsAccessKeySecret | quote }}
  {{- end }}
{{- end }}
