{{- if not .Values.importApi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.importApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: import-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  ENCRYPTION_SECRET_KEY: {{ .Values.cartoSecrets.encryptionSecretKey | b64enc | quote }}
  REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.clientSecrets.googleMapsApiKey | b64enc | quote }}
  {{- if eq .Values.customConfigValues.storageProvider "s3" }}
  IMPORT_ACCESSKEYID: {{ .Values.clientSecrets.awsAccessKeyId | b64enc | quote }}
  IMPORT_SECRETACCESSKEY: {{ .Values.clientSecrets.awsAccessKeySecret | b64enc | quote }}
  {{- end }}
{{- end }}
