{{- if and ((include "carto.disconnected.enabled" .)) (not .Values.cartoConfigValues.onlyRunRouter) }}
{{ $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
  "CARTO_INTERNAL_SERVICE_TOKEN"
  "ENCRYPTION_SECRET_KEY"
 ) "context" $ )}}
{{- $oidcClientSecret := and (eq .Values.appConfigValues.disconnected.protocol "oidc") .Values.appSecrets.authApiOidcClientSecret.value (not .Values.appSecrets.authApiOidcClientSecret.existingSecret.name) -}}
{{- $pgPassword := and .Values.externalPostgresql.authApiPassword (not (and .Values.externalPostgresql.existingSecret .Values.externalPostgresql.existingSecretAuthApiPasswordKey)) -}}
{{- if or $secretContent $oidcClientSecret $pgPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.authApi.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: auth-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if $secretContent }}
  {{ $secretContent | nindent 2 }}
  {{- end }}
  {{- if $oidcClientSecret }}
  CARTO_OIDC_CLIENT_SECRET: {{ .Values.appSecrets.authApiOidcClientSecret.value | b64enc | quote }}  # appSecrets.authApiOidcClientSecret.value
  {{- end }}
  {{- if $pgPassword }}
  ACCOUNTS_POSTGRES_PASSWORD: {{ .Values.externalPostgresql.authApiPassword | b64enc | quote }}  # externalPostgresql.authApiPassword
  {{- end }}
{{- end }}
{{- end }}
