{{- if and ((include "carto.disconnected.enabled" .)) (not .Values.cartoConfigValues.onlyRunRouter) }}
{{ $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
  "CARTO_INTERNAL_SERVICE_TOKEN"
  "ENCRYPTION_SECRET_KEY"
 ) "context" $ )}}
{{- $oidcClientSecret := and (eq .Values.authApi.protocol "oidc") .Values.authApi.oidc.clientSecret (not .Values.authApi.oidc.existingSecret.name) -}}
{{- if or $secretContent $oidcClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.authApi.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: auth-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if $secretContent }}
  {{ $secretContent | nindent 2 }}
  {{- end }}
  {{- if $oidcClientSecret }}
  CARTO_OIDC_CLIENT_SECRET: {{ .Values.authApi.oidc.clientSecret | b64enc | quote }}  # authApi.oidc.clientSecret
  {{- end }}
{{- end }}
{{- end }}
