apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: carto
spec:
  chart:
    name: carto
    chartVersion: 1.77.1
  values:
    replicated:
      enabled: true
    # License
    ## Carto Secrets
    cartoSecrets:
      encryptionSecretKey:
        value: '{{repl ConfigOption "kotsEncryptionSecretKey" }}'
      jwtApiSecret:
        value: '{{repl ConfigOption "kotsVarnishDebugSecret" }}'
      varnishDebugSecret:
        value: '{{repl ConfigOption "kotsJwtApiSecret" }}'
      varnishPurgeSecret:
        value: '{{repl ConfigOption "kotsVarnishPurgeSecret" }}'
      launchDarklySdkKey:
        value: '{{repl LicenseFieldValue "cartoFeaturesFlagSdkKey" }}'
      defaultGoogleServiceAccount:
        value: '{{repl ConfigOption "cartoPlatformGoogleSA" }}'
    # Carto Config Values
    cartoConfigValues:
      cartoAccApiDomain: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccApiDomain" "" | Base64Decode }}'
      cartoAccGcpProjectId: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccGcpProjectId" "" | Base64Decode }}'
      cartoAccGcpProjectRegion: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccGcpProjectRegion" "" | Base64Decode }}'
      cartoAuth0ClientId: '{{repl LicenseFieldValue "cartoAuthClientId" }}'
      cartoAuth0CustomDomain: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAuth0CustomDomain" "" | Base64Decode }}'
      selfHostedTenantId: '{{repl LicenseFieldValue "selfHostedId" }}'
      launchDarklyClientSideId: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "launchDarklyClientSideId" "" | Base64Decode }}'
      selfHostedGcpProjectId: '{{repl fromJson (LicenseFieldValue "cartoPlatformDefaultSA") | dig "project_id" "" }}'
      # customerPackageVersion: ""
      enableErrorResponseStackTrace: "false"
      cartoDataWarehouseEnabled: '{{repl ConfigOptionEquals "enableCDW" "1" }}'
      cartoSelfhostedDwLocation: '{{repl LicenseFieldValue "cartoDWLocation" }}'

    # Customizations
    ## App Secrets
    appSecrets:
      googleMapsApiKey:
        value: '{{repl ConfigOption "googleMapsAPIKey" }}'
      bigqueryOauth2ClientSecret:
        value: '{{repl ConfigOption "bigqueryOauthClientSecret" }}'
      googleCloudStorageServiceAccountKey:
        value: '{{repl ConfigOption "storageBucketsGcpServiceAccount" }}'
      awsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsAwsAccessKeyId" }}'
      awsAccessKeySecret:
        value: '{{repl ConfigOption "storageBucketsAwsAccessKeySecret" }}'
      azureStorageAccessKey:
        value: '{{repl ConfigOption "storageBucketsAzureAccessKey" }}'
      importAwsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsImportAwsAccessKeyId" }}'
      importAwsSecretAccessKey:
        value: '{{repl ConfigOption "storageBucketsImportAwsSecretAccessKey" }}'
      exportAwsSecretAccessKey:
        value: '{{repl ConfigOption "storageBucketsExportAwsSecretAccessKey" }}'
      exportAwsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsExportAwsAccessKeyId" }}'
      ldsHereApiKey:
        value: '{{repl ConfigOption "locationDataServicesHereCredentials" }}'
      ldsTomTomApiKey:
        value: '{{repl ConfigOption "locationDataServicesTomtomCredentials" }}'
      ldsGoogleApiKey:
        value: '{{repl ConfigOption "locationDataServicesGoogleCredentials" }}'
      ldsMapboxApiKey:
        value: '{{repl ConfigOption "locationDataServicesMapboxCredentials" }}'
      ldsTravelTimeAppId:
        value: '{{repl ConfigOption "locationDataServicesTraveltimeAppId" }}'
      ldsTravelTimeApiKey:
        value: '{{repl ConfigOption "locationDataServicesTraveltimeApiKey" }}'
    ## App Config Values
    appConfigValues:
      # domain
      selfHostedDomain: '{{repl ConfigOption "accessToSHDomain" }}'
      # buckets
      storageProvider: '{{repl fromJson (ConfigOption "storageBucketsProvider") | dig "provider" "" }}'
      workspaceImportsBucket: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "workspaceImportsBucket" "" }}'
      workspaceImportsPublic: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "workspaceImportsIsPublic" "" }}'
      workspaceThumbnailsBucket: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "thumbnailsBucket" "" }}'
      workspaceThumbnailsPublic: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "thumbnailsIsPublic" "" }}'
      workspaceExportsBucket: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "workspaceExportsBucket" "" }}'
      googleCloudStorageProjectId: '{{repl fromJson (ConfigOption "storageBucketsDetails") | dig "googleCloudStorageProjectId" "" }}'
      awsS3Region: '{{repl ConfigOption "storageBucketsAwsS3Region" }}'
      importAwsRoleArn: '{{repl ConfigOption "storageBucketsImportExportAwsArnRole" }}'
      awsExportBucket: '{{repl ConfigOption "storageBucketsExportAws" }}'
      awsExportBucketRegion: '{{repl ConfigOption "storageBucketsExportAwsRegion" }}'
      exportAwsRoleArn: '{{repl ConfigOption "storageBucketsImportExportAwsArnRole" }}'
      # other config
      httpCacheEnabled: "true"
      bigqueryOauth2ClientId: '{{repl ConfigOption "bigqueryOauthClientID" }}'
      enableTrackJS: "true"
      ssoOrganizationId: ""
      defaultAtLocation:
        bigquery: "carto-un.carto"
        snowflake: "CARTO.CARTO"
        redshift: "carto"
        postgres: "carto"

    ## Postgresql
    internalPostgresql:
      # Disable the internal Postgres
      enabled: false
    externalPostgresql:
      host: '{{repl ConfigOption "metadataDBHost" }}'
      port: '{{repl ConfigOption "metadataDBPort" }}'
      database: '{{repl ConfigOption "metadataDBName" }}'
      user: '{{repl ConfigOption "metadataDBUser" }}'
      password: '{{repl ConfigOption "metadataDBPassword" }}'
      sslEnabled: repl{{ if ConfigOptionEquals "metadataDBSSLMode" "1"}}truerepl{{ else }}falserepl{{ end }}
      sslCA: |
        repl{{- ConfigOptionData "metadataDBSSLCertificate" | nindent 8 }}

    ## Redis
    internalRedis:
      enabled: repl{{ if ConfigOptionEquals "externalRedisEnabled" "0"}}truerepl{{ else }}falserepl{{ end }}
    externalRedis:
      host: '{{repl ConfigOption "externalRedisHost" }}'
      port: '{{repl ConfigOption "externalRedisPort" }}'
      password: '{{repl ConfigOption "externalRedisPassword" }}'
      tlsEnabled: repl{{ if ConfigOptionEquals "externalRedisSSLMode" "ssl_mode_enable"}}truerepl{{ else }}falserepl{{ end }}
      tlsCA: |
        repl{{- ConfigOptionData "externalRedisSSLCertificate" | nindent 8 }}

    # Service Account
    commonBackendServiceAccount:
      enableGCPWorkloadIdentity: repl{{ if ConfigOptionEquals "googleWorkloadIdentityStatus" "enabled_on_apis"}}truerepl{{ else }}falserepl{{ end }}
      annotations:
        iam.gke.io/gcp-service-account: '{{repl ConfigOption "googleWorkloadIdentityEmail" }}'

    ## TLS Certs
    tlsCerts:
      httpsEnabled: repl{{ if ConfigOptionEquals "accessToCartoDefaultAccessCertificates" "tls_managed_certificates"}}falserepl{{ else }}truerepl{{ end }}
      autoGenerate: false
      customCerts: repl{{ if ConfigOptionEquals "accessToCartoDefaultAccessCertificates" "tls_custom_certificates"}}truerepl{{ else }}falserepl{{ end }}
      customCertificate: '{{repl ConfigOption "accessToSHCustomTLSTerminationCertFile" }}'
      customPrivateKey: '{{repl ConfigOption "accessToSHCustomTLSTerminationKeyFile" }}'
      generateManagedCerts: repl{{ if ConfigOptionEquals "accessToCartoDefaultAccessCertificates" "tls_managed_certificates"}}truerepl{{ else }}falserepl{{ end }}

    ## Access to Carto
    router:
      service:
        type: NodePort

  # Values from Advanced Configuration
  optionalValues:
    - when: '{{repl ConfigOptionEquals "enablePlatformAdvancedTuning" "1" }}'
      recursiveMerge: true
      values: repl{{ ConfigOption "platformAdvancedTuningValues" | nindent 8 }}
