---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: Carto
spec:
  title: CARTO
  icon: https://storage.googleapis.com/carto-published-resources-bucket/CARTO-Logo-Marker.png
  allowRollback: false
  supportMinimalRBACPrivileges: true
  statusInformers:
    # TODO: Add ingress, gateway or router service
    - deployment/carto-accounts-www
    - deployment/carto-cdn-invalidator-sub
    - deployment/carto-http-cache
    - deployment/carto-import-api
    - deployment/carto-import-worker
    - deployment/carto-lds-api
    - deployment/carto-maps-api
    - deployment/carto-notifier
    - deployment/carto-router
    - deployment/carto-sql-worker
    - deployment/carto-workspace-api
    - deployment/carto-workspace-subscriber
    - deployment/carto-workspace-www
    - '{{repl if ConfigOptionEquals "externalRedisEnabled" "0" }}deployment/carto-redis{{repl else}}{{repl end }}'
    - '{{repl if ConfigOptionEquals "aiApiEnabled" "1" }}deployment/carto-ai-api{{repl else}}{{repl end }}'
    - '{{repl if ConfigOptionEquals "aiApiEnabled" "1" }}deployment/carto-litellm{{repl else}}{{repl end }}'
  minKotsVersion: 1.107.4
  additionalImages:
    - gcr.io/carto-onprem-artifacts/tenant-requirements-checker:2024.4.17-rc.7
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: Carto
spec:
  descriptor:
    links:
      - description: Open CARTO platform
        url: "https://{{repl ConfigOption `cartoSelfHostedDomain` }}"
