apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: carto
spec:
  chart:
    name: carto
    chartVersion: 1.62.2
  values:
    # Add a value with the same name set to `enabled: false`
    # This excludes the SDK from KOTS installations
    replicated:
      enabled: false
    cartoSecrets:
      encryptionSecretKey:
        value: '{{repl ConfigOption "cartoSecrets_encryptionSecretKey" }}'
      jwtApiSecret:
        value: '{{repl ConfigOption "cartoSecrets_jwtApiSecret" }}'
      varnishDebugSecret:
        value: '{{repl ConfigOption "cartoSecrets_varnishDebugSecret" }}'
      varnishPurgeSecret:
        value: '{{repl ConfigOption "cartoSecrets_varnishPurgeSecret" }}'
      launchDarklySdkKey:
        value: '{{repl ConfigOption "cartoSecrets_launchDarklySdkKey" }}'
      defaultGoogleServiceAccount:
        value: '{{repl ConfigOption "cartoSecrets_defaultGoogleServiceAccount" }}'
    appConfigValues:
      selfHostedDomain: '{{repl ConfigOption "appConfigValues_selfHostedDomain" }}'
      workspaceImportsBucket: '{{repl ConfigOption "appConfigValues_workspaceImportsBucket" }}'
      workspaceThumbnailsBucket: '{{repl ConfigOption "appConfigValues_workspaceThumbnailsBucket" }}'
      thumbnailsBucketExternalURL: '{{repl ConfigOption "appConfigValues_thumbnailsBucketExternalURL" }}'
    cartoConfigValues:
      cartoAccApiDomain: '{{repl ConfigOption "cartoConfigValues_cartoAccApiDomain" }}'
      cartoAccGcpProjectId: '{{repl ConfigOption "cartoConfigValues_cartoAccGcpProjectId" }}'
      cartoAccGcpProjectRegion: '{{repl ConfigOption "cartoConfigValues_cartoAccGcpProjectRegion" }}'
      cartoAuth0ClientId: '{{repl ConfigOption "cartoConfigValues_cartoAuth0ClientId" }}'
      cartoAuth0CustomDomain: '{{repl ConfigOption "cartoConfigValues_cartoAuth0CustomDomain" }}'
      cartoSelfhostedDwLocation: '{{repl ConfigOption "cartoConfigValues_cartoSelfhostedDwLocation" }}'
      selfHostedTenantId: '{{repl ConfigOption "cartoConfigValues_selfHostedTenantId" }}'
      launchDarklyClientSideId: '{{repl ConfigOption "cartoConfigValues_launchDarklyClientSideId" }}'
      selfHostedGcpProjectId: '{{repl ConfigOption "cartoConfigValues_selfHostedGcpProjectId" }}'
      customerPackageVersion: '{{repl ConfigOption "cartoConfigValues_customerPackageVersion" }}'
    internalPostgresql:
      auth:
        password: '{{repl ConfigOption "internalConfig_postgresPassword" }}'
        postgresPassword: '{{repl ConfigOption "internalConfig_postgresPassword" }}'
    internalRedis:
      auth:
        password: '{{repl ConfigOption "internalConfig_redisPassword" }}'
    router:
      service:
        type: ClusterIP
        nodePorts:
          http: 8080
          https: 8443
      ingress:
        enabled: true
        ingressClassName: contour
        path: /
        tls: true
        # annotations:
        #   cert-manager.io/issuer: "selfsigned-issuer"
        #   kubernetes.io/tls-acme: "true"
        #   projectcontour.io/tls-cert-namespace: "default"
    tlsCerts:
      httpsEnabled: false
      autoGenerate: false
      existingSecret:
        # name: carto-tls--autogenerated
        name: carto-tls


