apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: carto
  annotations:
    kots.io/exclude: "true"
spec:
  chart:
    name: carto
    chartVersion: 1.77.1
  values:
    replicated:
      enabled: true
      platformDistribution: '{{repl ConfigOption "platformDistribution" }}'
      # TODO: To be removed when https://app.shortcut.com/cartoteam/story/383961/delete-podsecuritycontext-from-replicated-sdk-when-they-release-a-version-with-the-security-context-updated
      # is done
      podSecurityContext:
        enabled: true
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        supplementalGroups:
          - 1001
        seccompProfile:
          type: "RuntimeDefault"

    # License
    ## Carto Secrets
    cartoSecrets:
      encryptionSecretKey:
        value: '{{repl ConfigOption "kotsEncryptionSecretKey" }}'
      jwtApiSecret:
        value: '{{repl ConfigOption "kotsVarnishDebugSecret" }}'
      varnishDebugSecret:
        value: '{{repl ConfigOption "kotsJwtApiSecret" }}'
      varnishPurgeSecret:
        value: '{{repl ConfigOption "kotsVarnishPurgeSecret" }}'
      launchDarklySdkKey:
        value: '{{repl LicenseFieldValue "cartoFeaturesFlagSdkKey" }}'
      defaultGoogleServiceAccount:
        value: '{{repl ConfigOption "cartoPlatformGoogleSA" }}'
    # Carto Config Values
    cartoConfigValues:
      cartoAccApiDomain: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccApiDomain" "" | Base64Decode }}'
      cartoAccGcpProjectId: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccGcpProjectId" "" | Base64Decode }}'
      cartoAccGcpProjectRegion: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAccGcpProjectRegion" "" | Base64Decode }}'
      cartoAuth0ClientId: '{{repl LicenseFieldValue "cartoAuthClientId" }}'
      cartoAuth0CustomDomain: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "cartoAuth0CustomDomain" "" | Base64Decode }}'
      selfHostedTenantId: '{{repl LicenseFieldValue "selfHostedId" }}'
      launchDarklyClientSideId: '{{repl fromJson (ConfigOption "environmentCustomerPackageValues") | dig "launchDarklyClientSideId" "" | Base64Decode }}'
      selfHostedGcpProjectId: '{{repl (ConfigOption "projectId") }}'
      # customerPackageVersion: ""
      enableErrorResponseStackTrace: "false"
      cartoDataWarehouseEnabled: '{{repl ConfigOptionEquals "enableCDW" "1" }}'
      cartoSelfhostedDwLocation: '{{repl LicenseFieldValue "cartoDWLocation" }}'

    # Customizations
    ## App Secrets
    appSecrets:
      googleMapsApiKey:
        value: '{{repl ConfigOption "googleMapsAPIKey" }}'
      bigqueryOauth2ClientSecret:
        value: '{{repl ConfigOption "bigqueryOauthClientSecret" }}'
      googleCloudStorageServiceAccountKey:
        value: '{{repl ConfigOption "storageBucketsGcpServiceAccount" }}'
      awsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsAwsAccessKeyId" }}'
      awsAccessKeySecret:
        value: '{{repl ConfigOption "storageBucketsAwsAccessKeySecret" }}'
      azureStorageAccessKey:
        value: '{{repl ConfigOption "storageBucketsAzureAccessKey" }}'
      importAwsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsImportAwsAccessKeyId" }}'
      importAwsSecretAccessKey:
        value: '{{repl ConfigOption "storageBucketsImportAwsSecretAccessKey" }}'
      exportAwsSecretAccessKey:
        value: '{{repl ConfigOption "storageBucketsExportAwsSecretAccessKey" }}'
      exportAwsAccessKeyId:
        value: '{{repl ConfigOption "storageBucketsExportAwsAccessKeyId" }}'
      ldsHereApiKey:
        value: '{{repl ConfigOption "locationDataServicesHereCredentials" }}'
      ldsTomTomApiKey:
        value: '{{repl ConfigOption "locationDataServicesTomtomCredentials" }}'
      ldsGoogleApiKey:
        value: '{{repl ConfigOption "locationDataServicesGoogleCredentials" }}'
      ldsMapboxApiKey:
        value: '{{repl ConfigOption "locationDataServicesMapboxCredentials" }}'
      ldsTravelTimeAppId:
        value: '{{repl ConfigOption "locationDataServicesTraveltimeAppId" }}'
      ldsTravelTimeApiKey:
        value: '{{repl ConfigOption "locationDataServicesTraveltimeApiKey" }}'
    ## App Config Values
    appConfigValues:
      # domain
      selfHostedDomain: '{{repl ConfigOption "accessToSHDomain" }}'
      # buckets
      storageProvider: '{{repl fromJson (ConfigOption "storageBucketsProvider") | dig "provider" "" }}'
      workspaceImportsBucket: '{{repl ConfigOption "storageBucketsWorkspaceImports" }}'
      workspaceImportsPublic: repl{{ if ConfigOptionEquals "storageBucketsWorkspaceImportsIsPublic" "public"}}truerepl{{ else }}falserepl{{ end }}
      workspaceThumbnailsBucket: '{{repl ConfigOption "storageBucketsThumbnails" }}'
      workspaceThumbnailsPublic: repl{{ if ConfigOptionEquals "storageBucketsThumbnailsIsPublic" "public"}}truerepl{{ else }}falserepl{{ end }}
      workspaceExportsBucket: '{{repl ConfigOption "storageBucketsWorkspaceExports" }}'
      googleCloudStorageProjectId: '{{repl ConfigOption "storageBucketsGcpProjectId" }}'
      awsS3Region: '{{repl ConfigOption "storageBucketsAwsS3Region" }}'
      importAwsRoleArn: '{{repl ConfigOption "storageBucketsImportExportAwsArnRole" }}'
      awsExportBucket: '{{repl ConfigOption "storageBucketsExportAws" }}'
      awsExportBucketRegion: '{{repl ConfigOption "storageBucketsExportAwsRegion" }}'
      exportAwsRoleArn: '{{repl ConfigOption "storageBucketsImportExportAwsArnRole" }}'
      # other config
      httpCacheEnabled: "true"
      bigqueryOauth2ClientId: '{{repl ConfigOption "bigqueryOauthClientID" }}'
      enableTrackJS: "true"
      ssoOrganizationId: ""
      defaultAtLocation:
        bigquery: "carto-un.carto"
        snowflake: "CARTO.CARTO"
        redshift: "carto"
        postgres: "carto"

    ## Postgresql
    internalPostgresql:
      # Disable the internal Postgres
      enabled: false
    externalPostgresql:
      host: '{{repl ConfigOption "metadataDBHost" }}'
      port: '{{repl ConfigOption "metadataDBPort" }}'
      database: '{{repl ConfigOption "metadataDBName" }}'
      user: '{{repl ConfigOption "metadataDBUser" }}'
      password: '{{repl ConfigOption "metadataDBPassword" }}'
      sslEnabled: repl{{ if ConfigOptionEquals "metadataDBSSLMode" "1"}}truerepl{{ else }}falserepl{{ end }}
      sslCA: |
        repl{{- ConfigOptionData "metadataDBSSLCertificate" | nindent 8 }}

    ## Redis
    internalRedis:
      enabled: repl{{ if ConfigOptionEquals "externalRedisEnabled" "0"}}truerepl{{ else }}falserepl{{ end }}
    externalRedis:
      host: '{{repl ConfigOption "externalRedisHost" }}'
      port: '{{repl ConfigOption "externalRedisPort" }}'
      password: '{{repl ConfigOption "externalRedisPassword" }}'
      tlsEnabled: repl{{ if ConfigOptionEquals "externalRedisSSLMode" "ssl_mode_enable"}}truerepl{{ else }}falserepl{{ end }}
      tlsCA: |
        repl{{- ConfigOptionData "externalRedisSSLCertificate" | nindent 8 }}

    # Service Account
    commonBackendServiceAccount:
      enableGCPWorkloadIdentity: repl{{ if ConfigOptionEquals "googleWorkloadIdentityStatus" "enabled_on_apis"}}truerepl{{ else }}falserepl{{ end }}
      annotations:
        iam.gke.io/gcp-service-account: '{{repl ConfigOption "googleWorkloadIdentityEmail" }}'

    ## TLS Certs
    # FIXME: Deprecated in favor of router.tlsCertificates and ingress.tlsCertificates
    # Disable legacy tlsCerts
    tlsCerts:
      httpsEnabled: false
      autoGenerate: false

    ## Access to Carto
    # Router
    router:
      service:
        type: NodePort
      httpsEnabled: repl{{ if ConfigOptionEquals "customCerts" "true"}}truerepl{{ else }}falserepl{{ end }}
      tlsCertificates:
        certificateValueBase64: '{{repl ConfigOption "accessToSHCustomTLSCertFile" }}'
        privateKeyValueBase64: '{{repl ConfigOption "accessToSHCustomTLSKeyFile" }}'

    # Ingress
    ingress:
      enabled: repl{{ if ConfigOptionEquals "ingressEnabled" "true"}}truerepl{{ else }}falserepl{{ end }}
      tlsCertificates:
        customCerts:
          enabled: repl{{ if ConfigOptionEquals "customCerts" "true"}}truerepl{{ else }}falserepl{{ end }}
          certificateValueBase64: '{{repl ConfigOption "accessToSHCustomTLSCertFile" }}'
          privateKeyValueBase64: '{{repl ConfigOption "accessToSHCustomTLSKeyFile" }}'
        managedCerts:
          enabled: repl{{ if ConfigOptionEquals "gcpManagedCerts" "true"}}truerepl{{ else }}falserepl{{ end }}

  # Optional Values
  ## Values from Advanced Configuration
  optionalValues:
    # START: Temporary hack to fix some images not already released
    - when: "true"
      recursiveMerge: true
      values:
        workspaceMigrations:
          image:
            tag: 20240117pr15139
    # END

    ## Router & Ingress
    ## GKE
    - when: '{{repl and (ConfigOptionEquals "ingressEnabled" "true") (ConfigOptionEquals "platformDistribution" "gke") }}'
      recursiveMerge: true
      values:
        router:
          service:
            annotations:
              cloud.google.com/backend-config: '{"default": "carto-service-backend-config"}'
          ingress:
            annotations:
              networking.gke.io/v1beta1.FrontendConfig: "carto-ingress-frontend-config"
              kubernetes.io/ingress.class: "gce"
              kubernetes.io/ingress.global-static-ip-name: '{{repl ConfigOption "accessToCartoDefaultLBStaticIP" }}'

    # Managed certs
    - when: '{{repl and (ConfigOptionEquals "ingressEnabled" "true") (ConfigOptionEquals "platformDistribution" "gke") (ConfigOptionEquals "gcpManagedCerts" "true") }}'
      recursiveMerge: true
      values:
        router:
          ingress:
            annotations:
              networking.gke.io/managed-certificates: carto-ingress-managed-cert


    ## High Availability
    # High Availability Enable
    - when: '{{repl ConfigOptionEquals "enablePlatformHighAvailability" "1" }}'
      recursiveMerge: true
      values:
        importApi: &highAvailabilityEnabled
          autoscaling:
            enabled: true
            minReplicas: '{{repl ConfigOption "highAvailabilityMinReplicas" }}'
            maxReplicas: '{{repl ConfigOption "highAvailabilityMaxReplicas" }}'
        ldsApi: *highAvailabilityEnabled
        mapsApi: *highAvailabilityEnabled
        router: *highAvailabilityEnabled
        workspaceApi: *highAvailabilityEnabled
        workspaceWww: *highAvailabilityEnabled
        accountsWww: *highAvailabilityEnabled

    ## Advanced Tuning
    - when: '{{repl ConfigOptionEquals "enablePlatformAdvancedTuning" "1" }}'
      recursiveMerge: true
      values: repl{{ ConfigOption "platformAdvancedTuningValues" | nindent 8 }}
