---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: carto-config
spec:
  groups:

    - name: carto-secret-package
      title: CARTO secrets package
      description: Packages of secrets provided by CARTO
      items:
        # - name: app_config_values
        #   title: Customize Text Inputs
        #   help_text: "Copy the 'appConfigValues' yaml"
        #   type: text
        #   default: "null"  # That is going to leave the default provided by Helm
        - name: cartoSecrets_encryptionSecretKey
          title: cartoSecrets >> encryptionSecretKey
          help_text: "Copy the 'cartoSecrets.encryptionSecretKey.value' yaml"
          type: text
          required: true
          readonly: false  # Mandatory to persist the value
          hidden: true
          value: '{{repl RandomString 32 "[A-Za-z0-9]" }}'
        - name: cartoSecrets_jwtApiSecret
          title: cartoSecrets >> jwtApiSecret
          help_text: "Copy the 'cartoSecrets.jwtApiSecret.value' yaml"
          type: text
          required: true
          readonly: false  # Mandatory to persist the value
          hidden: true
          value: '{{repl RandomString 16 "[A-Za-z0-9]" }}'
        - name: cartoSecrets_varnishDebugSecret
          title: cartoSecrets >> varnishDebugSecret
          help_text: "Copy the 'cartoSecrets.varnishDebugSecret.value' yaml"
          type: text
          required: true
          readonly: false  # Mandatory to persist the value
          hidden: true
          value: '{{repl RandomString 16 "[A-Za-z0-9]" }}'
        - name: cartoSecrets_varnishPurgeSecret
          title: cartoSecrets >> varnishPurgeSecret
          help_text: "Copy the 'cartoSecrets.varnishPurgeSecret.value' yaml"
          type: text
          required: true
          readonly: false  # Mandatory to persist the value
          hidden: true
          value: '{{repl RandomString 16 "[A-Za-z0-9]" }}'
        - name: cartoSecrets_launchDarklySdkKey
          title: cartoSecrets >> launchDarklySdkKey
          help_text: "Copy the 'cartoSecrets.launchDarklySdkKey.value' yaml"
          type: text
          required: true
          hidden: true
          value: '{{repl LicenseFieldValue "cartoSelfhostedDwLocation" }}'

        - name: cartoSecrets_defaultGoogleServiceAccount
          title: defaultGoogleServiceAccount
          help_text: "Add the Google Service Account that should be used by CARTO"
          type: textarea
          required: true
          value: '{{repl LicenseFieldValue "defaultGoogleServiceAccount" }}'
          # Allow the user to edit the default SA
          hidden: false
          readonly: false

    - name: carto-values-package
      title: CARTO values package
      description: Packages of values provided by CARTO
      items:
        # - name: app_config_values
        #   title: Customize Text Inputs
        #   help_text: "Copy the 'appConfigValues' yaml"
        #   type: text
        #   default: "null"  # That is going to leave the default provided by Helm
        - name: appConfigValues_selfHostedDomain
          title: appConfigValues >> selfHostedDomain
          help_text: "Your domain (without protocol)"
          type: text
          required: true
          default: "carto3-onprem.lan"
        - name: appConfigValues_workspaceImportsBucket
          title: appConfigValues >> workspaceImportsBucket
          help_text: "Copy the 'appConfigValues.workspaceImportsBucket.value' yaml"
          type: text
          required: true
          value: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-client-storage'
          default: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-client-storage'
        - name: appConfigValues_workspaceThumbnailsBucket
          title: appConfigValues >> workspaceThumbnailsBucket
          help_text: "Copy the 'appConfigValues.workspaceThumbnailsBucket.value' yaml"
          type: text
          required: true
          value: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-thumbnails-storage'
          default: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-thumbnails-storage'
        - name: appConfigValues_thumbnailsBucketExternalURL
          title: appConfigValues >> thumbnailsBucketExternalURL
          help_text: "Copy the 'appConfigValues.thumbnailsBucketExternalURL.value' yaml"
          type: text
          required: true
          value: 'https://storage.googleapis.com/{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-thumbnails-storage'
          default: 'https://storage.googleapis.com/{{repl LicenseFieldValue "selfHostedGcpProjectId" }}-thumbnails-storage'

        - name: cartoConfigValues_cartoAuth0ClientId
          title: cartoConfigValues >> cartoAuth0ClientId
          help_text: "Copy the 'cartoConfigValues.cartoAuth0ClientId.value' yaml"
          type: text
          required: true
          hidden: true
          default: '{{repl LicenseFieldValue "cartoAuth0ClientId" }}'
          value: '{{repl LicenseFieldValue "cartoAuth0ClientId" }}'

        - name: cartoConfigValues_cartoSelfhostedDwLocation
          title: cartoConfigValues >> cartoSelfhostedDwLocation
          help_text: "Copy the 'cartoConfigValues.cartoSelfhostedDwLocation.value' yaml"
          type: text
          required: true
          default: '{{repl LicenseFieldValue "cartoSelfhostedDwLocation" }}'
          value: '{{repl LicenseFieldValue "cartoSelfhostedDwLocation" }}'
          hidden: true
        - name: cartoConfigValues_launchDarklyClientSideId
          title: cartoConfigValues >> launchDarklyClientSideId
          help_text: "Copy the 'cartoConfigValues.launchDarklyClientSideId.value' yaml"
          type: text
          required: true
          default: '{{repl LicenseFieldValue "launchDarklyClientSideId" }}'
          value: '{{repl LicenseFieldValue "launchDarklyClientSideId" }}'
          hidden: true
        - name: cartoConfigValues_selfHostedGcpProjectId
          title: cartoConfigValues >> selfHostedGcpProjectId
          help_text: "Copy the 'cartoConfigValues.selfHostedGcpProjectId.value' yaml"
          type: text
          required: true
          default: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}'
          value: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}'
          hidden: false
          readonly: true
        - name: cartoConfigValues_selfHostedTenantId
          title: cartoConfigValues >> selfHostedTenantId
          help_text: "Copy the 'cartoConfigValues.selfHostedTenantId.value' yaml"
          type: text
          required: true
          default: '{{repl LicenseFieldValue "selfHostedTenantId" }}'
          value: '{{repl LicenseFieldValue "selfHostedTenantId" }}'
          hidden: false
          readonly: true
        - name: cartoConfigValues_customerPackageVersion
          title: cartoConfigValues >> customerPackageVersion
          help_text: "Copy the 'cartoConfigValues.customerPackageVersion.value' yaml"
          type: text
          required: true
          default: "null"  # That is going to leave the default provided by Helm
    - name: internal-values-package
      title: CARTO internals
      description: Packages of internal values
      items:
        - name: internalConfig_postgresPassword
          title: internal Postgres Password
          type: text
          value: '{{repl RandomString 64}}'
          readonly: false
          hidden: false
        - name: internalConfig_redisPassword
          title: internal Redis Password
          type: text
          value: '{{repl RandomString 64}}'
          readonly: false
          hidden: false
    - name: carto-advanced-options
      title: Advanced Options
      description: Advanced options for the CARTO installation
      items:
        - name: cartoConfigValues_cartoAccApiDomain
          title: cartoConfigValues >> cartoAccApiDomain
          help_text: "Copy the 'cartoConfigValues.cartoAccApiDomain.value' yaml"
          type: text
          required: true
          value: 'accounts.app.carto.com'
          default: 'accounts.app.carto.com'
        - name: cartoConfigValues_cartoAccGcpProjectId
          title: cartoConfigValues >> cartoAccGcpProjectId
          help_text: "Copy the 'cartoConfigValues.cartoAccGcpProjectId.value' yaml"
          type: text
          required: true
          value: 'carto-acc-us-east1-1'
          default: 'carto-acc-us-east1-1'
        - name: cartoConfigValues_cartoAccGcpProjectRegion
          title: cartoConfigValues >> cartoAccGcpProjectRegion
          help_text: "Copy the 'cartoConfigValues.cartoAccGcpProjectRegion.value' yaml"
          type: text
          required: true
          value: 'us-east1-1'
          default: 'us-east1-1'
        - name: cartoConfigValues_cartoAuth0CustomDomain
          title: cartoConfigValues >> cartoAuth0CustomDomain
          help_text: "Copy the 'cartoConfigValues.cartoAuth0CustomDomain.value' yaml"
          type: text
          required: true
          value: 'auth.carto.com'
          default: 'auth.carto.com'

        #   default: "0"
        #   recommended: true
        # - name: example_default_value
        #   title: Text Example (with default value)
        #   type: text
        #   value: ""
        #   default: please change this value
        #   when: repl{{ ConfigOptionEquals "show_text_inputs" "1" }}
        # - name: api_token
        #   title: API token
        #   type: password
        #   props:
        #     rows: 5
        #   when: repl{{ ConfigOptionEquals "show_text_inputs" "1" }}
        #   validation:
        #     regex: 
        #       pattern: ^(?:[\w@#$%^&+=!*()_\-{}[\]:;"'<>,.?\/|]){8,16}$
        #       message: The password must be between 8 and 16 characters long and can contain a combination of uppercase letters, lowercase letters, digits, and special characters.
        # - name: readonly_text_left
        #   title: Readonly Text
        #   type: text
        #   value: "{{repl RandomString 10}}"
        #   readonly: true
        #   when: repl{{ ConfigOptionEquals "show_text_inputs" "1" }}
        # - name: hidden_text
        #   title: Secret Key
        #   type: password
        #   hidden: true
        #   value: "{{repl RandomString 40}}"
