apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: carto
spec:
  chart:
    name: carto
    chartVersion: 1.77.1
  values:
    replicated:
      enabled: true

    # License
    ## Carto Secrets
    cartoSecrets:
      encryptionSecretKey:
        value: '{{repl LicenseFieldValue "encryptionSecretKey" }}'
      jwtApiSecret:
        value: '{{repl LicenseFieldValue "jwtApiSecret" }}'
      varnishDebugSecret:
        value: '{{repl LicenseFieldValue "varnishDebugSecret" }}'
      varnishPurgeSecret:
        value: '{{repl LicenseFieldValue "varnishPurgeSecret" }}'
      launchDarklySdkKey:
        value: '{{repl LicenseFieldValue "launchDarklySdkKey" }}'
      defaultGoogleServiceAccount:
        value: '{{repl ConfigOption "defaultGoogleServiceAccount" }}'
    # Carto Config Values
    cartoConfigValues:
      cartoAccApiDomain: '{{repl LicenseFieldValue "cartoAccApiDomain" }}'
      cartoAccGcpProjectId: '{{repl LicenseFieldValue "cartoAccGcpProjectId" }}'
      cartoAccGcpProjectRegion: '{{repl LicenseFieldValue "cartoAccGcpProjectRegion" }}'
      cartoAuth0ClientId: '{{repl LicenseFieldValue "cartoAuth0ClientId" }}'
      cartoAuth0CustomDomain: '{{repl LicenseFieldValue "cartoAuth0CustomDomain" }}'
      selfHostedTenantId: '{{repl LicenseFieldValue "selfHostedTenantId" }}'
      launchDarklyClientSideId: '{{repl LicenseFieldValue "launchDarklyClientSideId" }}'
      selfHostedGcpProjectId: '{{repl LicenseFieldValue "selfHostedGcpProjectId" }}'
      customerPackageVersion: '{{repl LicenseFieldValue "customerPackageVersion" }}'
      enableErrorResponseStackTrace: "false"
      cartoDataWarehouseEnabled: '{{repl ConfigOptionEquals "enableCDW" "1" }}'
      cartoSelfhostedDwLocation: '{{repl LicenseFieldValue "cartoSelfhostedDwLocation" }}'

    # Customizations
    ## App Secrets
    appSecrets:
      googleMapsApiKey:
        value: '{{repl ConfigOption "googleMapsAPIKey" }}'
      bigqueryOauth2ClientSecret:
        value: '{{repl ConfigOption "bigqueryOauthClientSecret" }}'
      googleCloudStorageServiceAccountKey:
        value: ""
      awsAccessKeyId:
        value: ""
      awsAccessKeySecret:
        value: ""
      azureStorageAccessKey:
        value: ""
      importAwsAccessKeyId:
        value: ""
      importAwsSecretAccessKey:
        value: ""
      exportAwsSecretAccessKey:
        value: ""
      exportAwsAccessKeyId:
        value: ""
      ldsHereApiKey:
        value: ""
      ldsTomTomApiKey:
        value: ""
      ldsGoogleApiKey:
        value: ""
      ldsMapboxApiKey:
        value: ""
      ldsTravelTimeAppId:
        value: ""

    ## App Config Values
    appConfigValues:
      # domain
      selfHostedDomain: '{{repl ConfigOption "accessToSHDomain" }}'
      # buckets
      storageProvider: '{{repl fromJson (ConfigOption "storageBucketsProvider") | dig "provider" "" }}'
      workspaceImportsBucket:
      workspaceImportsPublic: false
      workspaceThumbnailsBucket: 
      workspaceThumbnailsPublic: '{{repl (ConfigOptionEquals "storageBucketsBehaviour" "default") }}'
      importAwsRoleArn: ""
      exportAwsRoleArn: ""
      awsExportBucket: ""
      awsExportBucketRegion: ""
      awsS3Region: ""
      # thumbnailsBucketExternalURL: ""
      # googleCloudStorageProjectId: ""

      httpCacheEnabled: "true"
      bigqueryOauth2ClientId: '{{repl ConfigOption "bigqueryOauthClientID" }}'
      enableTrackJS: "true"
      ssoOrganizationId: ""
      defaultAtLocation: 
        bigquery: "carto-un.carto"
        snowflake: "CARTO.CARTO"
        redshift: "carto"
        postgres: "carto"
      workspaceExportsBucket: ""

    ## Postgresql
    internalPostgresql:
      # Disable the internal Postgres
      enabled: false
    externalPostgresql:
      host: '{{repl ConfigOption "metadataDBHost" }}'
      port: '{{repl ConfigOption "metadataDBPort" }}'
      database: '{{repl ConfigOption "metadataDBName" }}'
      user: '{{repl ConfigOption "metadataDBUser" }}'
      password: '{{repl ConfigOption "metadataDBPassword" }}'
      sslEnabled: repl{{ if ConfigOptionEquals "metadataDBSSLMode" "ssl_mode_enable"}}truerepl{{ else }}falserepl{{ end }}
      sslCA: |
        repl{{- ConfigOptionData "metadataDBSSLCertificate" | nindent 8 }}

    ## Redis
    internalRedis:
      enabled: repl{{ if ConfigOptionEquals "redisCacheBehaviour" "internal"}}truerepl{{ else }}falserepl{{ end }}
    externalRedis:
      host: '{{repl ConfigOption "externalRedisHost" }}'
      port: '{{repl ConfigOption "externalRedisPort" }}'
      password: '{{repl ConfigOption "externalRedisPassword" }}'
      tlsEnabled: repl{{ if ConfigOptionEquals "externalRedisSSLMode" "ssl_mode_enable"}}truerepl{{ else }}falserepl{{ end }}
      tlsCA: |
        repl{{- ConfigOptionData "externalRedisSSLCertificate" | nindent 8 }}

    # Service Account
    commonBackendServiceAccount:
      enableGCPWorkloadIdentity: repl{{ if ConfigOptionEquals "googleWorkloadIdentityStatus" "enabled_on_apis"}}truerepl{{ else }}falserepl{{ end }}
      annotations:
        iam.gke.io/gcp-service-account: '{{repl ConfigOption "googleWorkloadIdentityEmail" }}'

    ## TLS Certs
    tlsCerts:
      httpsEnabled: repl{{ if ConfigOptionEquals "accessToSHCustomTLSTerminationNotRequired" "0"}}truerepl{{ else }}falserepl{{ end }}
      autoGenerate: repl{{ if ConfigOptionEquals "accessToSHCustomTLSTerminationCertsBehaviour" "tls_selfsigned_certificates"}}truerepl{{ else }}falserepl{{ end }}
      certKey: '{{repl ConfigOption "accessToSHCustomTLSTerminationCertFile" }}'
      keyKey: '{{repl ConfigOption "accessToSHCustomTLSTerminationKeyFile" }}'

    ## Carto Components
    router:
      service:
        type: ClusterIP
        nodePorts:
          http: 8080
          https: 8443
