{{- if not .Values.accountsWww.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.accountsWww.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: accounts-www
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  CARTO_DATA_WAREHOUSE_ENABLED: {{ .Values.cartoConfigValues.cartoDataWarehouseEnabled | quote }}
  CARTO_SELFHOSTED_VERSION: {{ .Chart.AppVersion | quote }}
  LOG_LEVEL: {{ .Values.appConfigValues.logLevel | quote }}
  PORT: {{ .Values.accountsWww.containerPorts.http | quote }}
  REACT_APP_ACCOUNTS_API_URL: "https://{{ .Values.cartoConfigValues.cartoAccApiDomain }}"
  REACT_APP_ACCOUNTS_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc/"
  REACT_APP_AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  REACT_APP_CLIENT_ID: {{ .Values.cartoConfigValues.cartoAuth0ClientId | quote }}
  REACT_APP_CUSTOM_TENANT: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  REACT_APP_WORKSPACE_URL_TEMPLATE: "https://{tenantDomain}"
  THUMBNAILS_BUCKET_EXTERNAL_URL: {{ .Values.appConfigValues.thumbnailsBucketExternalURL | quote }}
  REACT_APP_ACCOUNTS_WWW_ENABLE_TRACKJS: {{ .Values.appConfigValues.enableTrackJS | quote }}
  {{- if .Values.appConfigValues.ssoOrganizationId }}
  REACT_APP_ORGANIZATION_ID: {{ .Values.appConfigValues.ssoOrganizationId }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraConnectSrc }}
  CARTO_CSP_EXTRA_CONNECT_SRC: {{ .Values.appConfigValues.customCSP.extraConnectSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraScriptSrc }}
  CARTO_CSP_EXTRA_SCRIPT_SRC: {{ .Values.appConfigValues.customCSP.extraScriptSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraStyleSrc }}
  CARTO_CSP_EXTRA_STYLE_SRC: {{ .Values.appConfigValues.customCSP.extraStyleSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraFontSrc }}
  CARTO_CSP_EXTRA_FONT_SRC: {{ .Values.appConfigValues.customCSP.extraFontSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraImgSrc }}
  CARTO_CSP_EXTRA_IMG_SRC: {{ .Values.appConfigValues.customCSP.extraImgSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraFrameSrc }}
  CARTO_CSP_EXTRA_FRAME_SRC: {{ .Values.appConfigValues.customCSP.extraFrameSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraFrameAncestors }}
  CARTO_CSP_EXTRA_FRAME_ANCESTORS: {{ .Values.appConfigValues.customCSP.extraFrameAncestors | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraWorkerSrc }}
  CARTO_CSP_EXTRA_WORKER_SRC: {{ .Values.appConfigValues.customCSP.extraWorkerSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraChildSrc }}
  CARTO_CSP_EXTRA_CHILD_SRC: {{ .Values.appConfigValues.customCSP.extraChildSrc | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.customCSP.extraDefaultSrc }}
  CARTO_CSP_EXTRA_DEFAULT_SRC: {{ .Values.appConfigValues.customCSP.extraDefaultSrc | quote }}
  {{- end }}
{{- end }}
