version: '2'

services:
  router:
    image: docker.io/bitnami/nginx:1.21
    ports:
      - '80:8080'
    volumes:
      - ./router/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/reverse_proxy.conf
    environment:
      - BITNAMI_DEBUG=true

  workspace-www-fake:
    image: docker.io/bitnami/nginx:1.21
    volumes:
      - ./workspace-www/:/app/
    environment:
      - BITNAMI_DEBUG=true

  workspace-api-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    - redis
    command: sh -c 'npm install && npm start'
    volumes:
      - ./workspace-api-fake/:/app

  workspace-subscriber-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    command: sh -c 'npm install && npm start'
    volumes:
      - ./workspace-subscriber-fake/:/app

  maps-api-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    - redis
    command: sh -c 'npm install && npm start'
    volumes:
      - ./maps-api-fake/:/app

  sql-api-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    - redis
    command: sh -c 'npm install && npm start'
    volumes:
      - ./sql-api-fake/:/app

  import-api-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    command: sh -c 'npm install && npm start'
    volumes:
      - ./import-api-fake/:/app

  import-worker-fake:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    depends_on:
    - workspace-postgresql
    command: sh -c 'npm install && npm start'
    volumes:
      - ./import-worker-fake/:/app

  workspace-postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=carto3_workspace
      - POSTGRESQL_USERNAME=carto3
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: docker.io/bitnami/redis:5.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local