{{- if not .Values.aiApi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.aiApi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ai-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretVars := list "AI_API_JWT_SECRET" "WORKSPACE_OPENAI_API_KEY" "GEMINI_API_KEY" -}}
  {{- include "carto._utils.generateSecretObjects" (dict "vars" $secretVars "context" .) | nindent 2 }}
{{- end }} 