{{- if and (.Values.aiApi.enabled) (not .Values.cartoConfigValues.onlyRunRouter) }}
{{ $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
  "BIGQUERY_OAUTH2_CLIENT_SECRET"
  "CARTO_SELFHOSTED_INSTANCE_ID"
  "IMPORT_AWS_ACCESS_KEY_ID"
  "IMPORT_AWS_SECRET_ACCESS_KEY"
  "WORKSPACE_JWT_SECRET"
  "WORKSPACE_OPENAI_API_KEY"
  "GITBOOK_API_TOKEN"
  "LAUNCHDARKLY_SDK_KEY"
 ) "context" $ )}}
{{- if $secretContent }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.aiApi.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ai-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $secretContent | nindent 2 }}
{{- end }}
{{- end }}
