{{- if (include "carto.baseUrl" .) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.importWorker.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: import-worker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.cartoConfigValues.selfHostedTenantId }}
  replicas: {{ .Values.importWorker.replicaCount }}
  {{- else }}
  replicas: 0
  {{- end }}
  {{- if .Values.importWorker.updateStrategy }}
  strategy: {{- toYaml .Values.importWorker.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: import-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/import-worker/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/import-worker/secret.yaml") . | sha256sum }}
        {{- if .Values.importWorker.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: import-worker
        {{- if .Values.importWorker.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.importWorker.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.importWorker.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.importWorker.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.importWorker.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.importWorker.podAffinityPreset "component" "import-worker" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.importWorker.podAntiAffinityPreset "component" "import-worker" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.importWorker.nodeAffinityPreset.type "key" .Values.importWorker.nodeAffinityPreset.key "values" .Values.importWorker.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.importWorker.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.importWorker.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.importWorker.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.importWorker.priorityClassName }}
      priorityClassName: {{ .Values.importWorker.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.importWorker.schedulerName }}
      schedulerName: {{ .Values.importWorker.schedulerName | quote }}
      {{- end }}
      {{- if .Values.importWorker.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.importWorker.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.internalPostgresql.enabled }}
        {{ include "carto.postgresql-init-container" (dict "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.importWorker.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: import-worker
          image: "{{ .Values.importWorker.image.name }}:{{- include "carto.importWorker.tag" . -}}"
          imagePullPolicy: {{ .Values.importWorker.image.pullPolicy }}
          {{- if .Values.importWorker.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.importWorker.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.importWorker.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.importWorker.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              npm run start:built:subscriber
          {{- end }}
          env:
            - name: WORKSPACE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.key" . }}
            {{- if .Values.importWorker.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if not .Values.importWorker.existingConfigMap }}
            - configMapRef:
                name: {{ template "carto.importWorker.fullname" . }}
            {{- end }}
            {{- if .Values.importWorker.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.importWorker.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.importWorker.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.importWorker.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- if not .Values.importWorker.existingSecret }}
            - secretRef:
                name: {{ include "carto.importWorker.secretName" . }}
            {{- end }}
          {{- if .Values.importWorker.resources }}
          resources: {{- toYaml .Values.importWorker.resources | nindent 12 }}
          {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.importWorker.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.importWorker.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.importWorker.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.importWorker.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: google-secret
              mountPath: /usr/src/certs/{{ template "carto.google.secretKey" . }}
              subPath: {{ template "carto.google.secretKey" . }}
          {{- if .Values.importWorker.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.importWorker.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.importWorker.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: google-secret
          secret:
            secretName: {{ include "carto.google.secretName" . }}
        {{- if .Values.importWorker.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.importWorker.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
