{{- if not .Values.importWorker.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.importWorker.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: import-worker
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  ENCRYPTION_SECRET_KEY: {{ .Values.cartoSecretsValues.encryptionSecretKey | b64enc | quote }}
  REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.customSecretsValues.googleMapsApiKey | b64enc | quote }}
  {{- if eq .Values.appConfigValues.storageProvider "s3" }}
  IMPORT_ACCESSKEYID: {{ .Values.customSecretsValues.awsAccessKeyId | b64enc | quote }}
  IMPORT_SECRETACCESSKEY: {{ .Values.customSecretsValues.awsAccessKeySecret | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.appConfigValues.storageProvider "azure-blob" }}
  IMPORT_STORAGE_ACCESSKEY: {{ .Values.customSecretsValues.azureStorageAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
