{{- if and (.Values.importWorker.serviceAccount.create) (eq .Values.workloadIdentityConfig.enableWorkloadIdentity "false") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: import-worker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "carto.importWorker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.importWorker.serviceAccount.automountServiceAccountToken }}
{{- end }}
