{{- if not .Values.http-cache.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.http-cache.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: http-cache
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  .secret.env: |
    # Common configuration
    # CARTO self hosted sensitive information
    VARNISH_DEBUG_SECRET={{ .Values.cartoSecrets.varnishDebugSecret }}
    VARNISH_PURGE_SECRET={{ .Values.cartoSecrets.varnishPurgeSecret }}
{{- end }}
