{{- if and ((include "carto.disconnected.enabled" .)) (not .Values.cartoConfigValues.onlyRunRouter) }}
{{ $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
  "NATS_AUTH_TOKEN"
 ) "context" $ )}}
{{- if $secretContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.nats.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: nats
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ $secretContent | nindent 2 }}
{{- end }}
{{- end }}
