{{- if not .Values.litellm.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.litellm.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: litellm
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  PORT: {{ .Values.litellm.containerPorts.http | quote }}
  LOG_LEVEL: {{ .Values.appConfigValues.logLevel | quote }}
  CARTO_SELFHOSTED_VERSION: {{ .Chart.AppVersion | quote }}
  {{- if eq .Values.appConfigValues.logLevel "debug" }}
  CARTO_TRACING_MODE: "local"
  {{- end }}
  # Production Environment Variables (following official LiteLLM documentation)
  {{- range $key, $value := .Values.litellm.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Redis Configuration (individual params for 80 RPS improvement)
  REDIS_HOST: {{ include "carto.redis.host" . }}
  REDIS_PORT: {{ include "carto.redis.port" . }}
  REDIS_DB: "1"
  # Database Configuration
  DATABASE_URL: "postgresql://{{ include "carto.postgresql.user" . }}:@{{ include "carto.postgresql.host" . }}:{{ include "carto.postgresql.port" . }}/litellm"
  {{- if .Values.externalProxy.enabled }}
  HTTPS_PROXY: {{ include "carto.proxy.computedConnectionString" . }}
  HTTP_PROXY: {{ include "carto.proxy.computedConnectionString" . }}
  {{- if gt (len .Values.externalProxy.excludedDomains) 0 }}
  NO_PROXY: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  no_proxy: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.litellm.config.enabled }}
  # LiteLLM Production Configuration File
  config.yaml: |
    model_list:
    {{- range .Values.litellm.config.models }}
    - model_name: {{ .model_name }}
      litellm_params:
        {{- toYaml .litellm_params | nindent 8 }}
    {{- end }}
    
    litellm_settings:
      {{- toYaml .Values.litellm.config.litellm_settings | nindent 6 }}
    
    general_settings:
      {{- toYaml .Values.litellm.config.general_settings | nindent 6 }}
    
    router_settings:
      {{- toYaml .Values.litellm.config.router_settings | nindent 6 }}
  {{- end }}
{{- end }} 