{{- if and (.Values.litellm.enabled) (not .Values.cartoConfigValues.onlyRunRouter) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.litellm.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: litellm
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.litellm.replicaCount }}
  {{- if .Values.litellm.updateStrategy }}
  strategy: {{- toYaml .Values.litellm.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: litellm
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/litellm/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/litellm/secret.yaml") . | sha256sum }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- if .Values.litellm.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.litellm.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: litellm
        {{- if .Values.litellm.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.litellm.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.commonSA.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.litellm.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.litellm.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.litellm.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.litellm.podAffinityPreset "component" "litellm" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.litellm.podAntiAffinityPreset "component" "litellm" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.litellm.nodeAffinityPreset.type "key" .Values.litellm.nodeAffinityPreset.key "values" .Values.litellm.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.litellm.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.litellm.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.litellm.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.litellm.priorityClassName }}
      priorityClassName: {{ .Values.litellm.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.litellm.schedulerName }}
      schedulerName: {{ .Values.litellm.schedulerName | quote }}
      {{- end }}
      {{- if .Values.litellm.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.litellm.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.litellm.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.litellm.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.litellm.terminationGracePeriodSeconds }}
      containers:
        - name: litellm
          image: {{ template "carto.litellm.image" . }}
          imagePullPolicy: {{ .Values.litellm.image.pullPolicy }}
          {{- if .Values.litellm.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.litellm.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.litellm.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.litellm.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              #TODO: add args for litellm
          {{- end }}
          env:
            - name: LITELLM_MIGRATION_DIR
              value: /tmp/prisma/migrations    
            {{/* TODO: add secret for litellm */}}
            {{- include "carto._utils.generateSecretDefs" (dict "vars" (list
              "CARTO_SELFHOSTED_INSTANCE_ID"
              "ENCRYPTION_SECRET_KEY"
              "EXPORTS_S3_BUCKET_ACCESS_KEY_ID"
              "EXPORTS_S3_BUCKET_SECRET_ACCESS_KEY"
              "MAPS_API_V3_JWT_SECRET"             ) "context" $ ) | nindent 12 }}
            {{- if .Values.litellm.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.litellm.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "carto.litellm.configmapName" . }}
            {{/* TODO: add secret for litellm */}}
            {{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
              "CARTO_SELFHOSTED_INSTANCE_ID"
              "ENCRYPTION_SECRET_KEY"
              "EXPORTS_S3_BUCKET_ACCESS_KEY_ID"
              "EXPORTS_S3_BUCKET_SECRET_ACCESS_KEY"
              "MAPS_API_V3_JWT_SECRET"
             ) "context" $ ) -}}
            {{- if $secretContent }}
            - secretRef:
                name: {{ include "carto.litellm.secretName" . }}
            {{- end }}
            {{- if .Values.litellm.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.litellm.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.litellm.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.litellm.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.litellm.resources }}
          resources: {{- toYaml .Values.litellm.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.litellm.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.litellm.livenessProbe.enabled }}
          {{/* TODO: Review liveness probe for litellm */}}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.litellm.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- else if .Values.litellm.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.litellm.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.litellm.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- else if .Values.litellm.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.litellm.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.litellm.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- else if .Values.litellm.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.litellm.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.litellm.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/proxy_server_config.yaml
            subPath: config.yaml
          - name: litellm-migration-dir
            mountPath: /tmp/prisma/migrations
            {{- if .Values.litellm.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.litellm.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.litellm.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.litellm.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
        # Required for read-only filesystem
        - name: litellm-migration-dir
          emptyDir: {}
        {{/* TODO: review volumes to add for litellm */}}
        {{- if .Values.litellm.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.litellm.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }} 