{{- if not .Values.litellm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.litellm.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: litellm
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretVars := list "LITELLM_LICENSE" "LITELLM_MASTER_KEY" "LITELLM_SALT_KEY" "WORKSPACE_OPENAI_API_KEY" "GEMINI_API_KEY" -}}
  {{- include "carto._utils.generateSecretObjects" (dict "vars" $secretVars "context" .) | nindent 2 }}
  # Database password
  {{- include "carto._utils.generateSecretDef" (dict "var" "POSTGRES_PASSWORD" "context" .) | nindent 2 }}
  # Redis password
  {{- include "carto._utils.generateSecretDef" (dict "var" "REDIS_PASSWORD" "context" .) | nindent 2 }}
  # Additional production secrets from environment config
  {{- range $key, $value := .Values.litellm.environment }}
  {{- if or (contains "KEY" $key) (contains "SECRET" $key) (contains "PASSWORD" $key) (contains "TOKEN" $key) }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }} 