{{- if and (.Values.litellm.enabled) (not .Values.cartoConfigValues.onlyRunRouter) }}
{{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
  "CARTO_SELFHOSTED_INSTANCE_ID"
  "ENCRYPTION_SECRET_KEY"
  "EXPORTS_S3_BUCKET_ACCESS_KEY_ID"
  "EXPORTS_S3_BUCKET_SECRET_ACCESS_KEY"
  "MAPS_API_V3_JWT_SECRET"
  "LITELLM_MASTER_KEY"
  "LITELLM_SALT_KEY"
 ) "context" $ ) -}}
{{- if $secretContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.litellm.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: litellm
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{ $secretContent | nindent 2 }}
{{- end }}
{{- end }}