{{- if (include "carto.baseUrl" .) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.router.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: router
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.router.replicaCount }}
  {{- if .Values.router.updateStrategy }}
  strategy: {{- toYaml .Values.router.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: router
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/router/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/router/secret.yaml") . | sha256sum }}
        {{- if .Values.router.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.router.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: router
        {{- if .Values.router.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.router.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.router.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.router.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.router.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.router.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.router.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.router.podAffinityPreset "component" "router" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.router.podAntiAffinityPreset "component" "router" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.router.nodeAffinityPreset.type "key" .Values.router.nodeAffinityPreset.key "values" .Values.router.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.router.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.router.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.router.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.router.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.router.priorityClassName }}
      priorityClassName: {{ .Values.router.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.router.schedulerName }}
      schedulerName: {{ .Values.router.schedulerName | quote }}
      {{- end }}
      {{- if .Values.router.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.router.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.postgresql.enabled }}
        {{ include "carto.postgresql-init-container" (dict "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.router.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.router.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: router
          image: "{{ .Values.router.image.name }}:{{- include "carto.router.tag" . -}}"
          imagePullPolicy: {{ .Values.router.image.pullPolicy }}
          {{- if .Values.router.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.router.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.router.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.router.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.router.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.router.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              set -a
              . /secret/.secret.env
              ROUTER_RESOLVER="$(grep nameserver /etc/resolv.conf  | awk '{print $2}')"
              /docker-entrypoint.sh nginx -g "daemon off;"
          {{- end }}
          env:
            {{- if .Values.router.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.router.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if not .Values.router.existingConfigMap }}
            - configMapRef:
                name: {{ template "carto.router.fullname" . }}
            {{- end }}
            {{- if .Values.router.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.router.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.router.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.router.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.router.resources }}
          resources: {{- toYaml .Values.router.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.router.containerPorts.http }}
            - name: https
              containerPort: {{ .Values.router.containerPorts.https }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.router.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.router.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- else if .Values.router.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.router.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.router.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.router.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- else if .Values.router.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.router.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.router.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.router.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- else if .Values.router.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.router.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.router.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.router.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: secret-env
              mountPath: /secret
            - name: google-secret
              mountPath: /usr/src/certs/{{ template "carto.google.secretKey" . }}
              subPath: {{ template "carto.google.secretKey" . }}
            - name: tls-secret
              mountPath: /usr/src/certs/{{ template "carto.tlsCerts.secretCAKey" . }}
              subPath: {{ template "carto.tlsCerts.secretCAKey" . }}
            - name: tls-secret
              mountPath: /usr/src/certs/{{ template "carto.tlsCerts.secretCertKey" . }}
              subPath: {{ template "carto.tlsCerts.secretCertKey" . }}
            - name: tls-secret
              mountPath: /usr/src/certs/{{ template "carto.tlsCerts.secretKeyKey" . }}
              subPath: {{ template "carto.tlsCerts.secretKeyKey" . }}
          {{- if .Values.router.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.router.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.router.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.router.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: secret-env
          secret:
            secretName: {{ include "carto.router.secretName" . }}
        - name: tls-secret
          secret:
            secretName: {{ include "carto.tlsCerts.secretName" . }}
        - name: google-secret
          secret:
            secretName: {{ include "carto.google.secretName" . }}
        {{- if .Values.router.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.router.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
