{{- if (include "carto.baseUrl" .) }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "carto.workspaceApi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: workspace-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.workspaceApi.replicaCount }}
  {{- if .Values.workspaceApi.updateStrategy }}
  strategy: {{- toYaml .Values.workspaceApi.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: workspace-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/workspace-api/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/workspace-api/secret.yaml") . | sha256sum }}
        {{- if .Values.workspaceApi.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: workspace-api
        {{- if .Values.workspaceApi.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "carto.workspaceApi.serviceAccountName" . }}
      {{- include "carto.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.workspaceApi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.workspaceApi.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.workspaceApi.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.workspaceApi.podAffinityPreset "component" "workspace-api" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.workspaceApi.podAntiAffinityPreset "component" "workspace-api" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.workspaceApi.nodeAffinityPreset.type "key" .Values.workspaceApi.nodeAffinityPreset.key "values" .Values.workspaceApi.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.workspaceApi.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.workspaceApi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.workspaceApi.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.workspaceApi.priorityClassName }}
      priorityClassName: {{ .Values.workspaceApi.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.workspaceApi.schedulerName }}
      schedulerName: {{ .Values.workspaceApi.schedulerName | quote }}
      {{- end }}
      {{- if .Values.workspaceApi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.workspaceApi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.diagnosticMode.enabled }}
      initContainers:
        {{- if .Values.internalPostgresql.enabled }}
        {{ include "carto.postgresql-init-container" (dict "context" $ "admin" "true") | nindent 8 }}
        {{- end }}
        {{- if .Values.internalRedis.enabled }}
        {{ include "carto.redis-init-container" . | nindent 8 }}
        {{- end }}
        - name: workspace-migrations
          image: {{ template "carto.workspaceMigrations.image" . }}
          imagePullPolicy: {{ .Values.workspaceMigrations.image.pullPolicy }}
          {{- if .Values.workspaceMigrations.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.workspaceMigrations.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.workspaceMigrations.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceMigrations.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.workspaceMigrations.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceMigrations.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - -ec
            - |
              /usr/src/app/onprem-init-db.sh
          {{- end }}
          env:
            - name: POSTGRES_ADMIN_USER
              value: {{ include "carto.postgresql.adminUser" . }}
            - name: POSTGRES_LOGIN_USER
              value: {{ include "carto.postgresql.internalAdminUser" . }}
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.adminKey" . }}
            - name: WORKSPACE_POSTGRES_INTERNAL_USER
              value: {{ include "carto.postgresql.internalUser" . }}
            - name: WORKSPACE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.key" . }}
            - name: WORKSPACE_POSTGRES_SSL_MODE
              {{- if .Values.externalPostgresql.sslEnabled }}
              value: "require"
              {{- else }}
              value: "disable"
              {{- end }}
            {{- include "carto._utils.generateSecretDefs" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "WORKSPACE_THUMBNAILS_ACCESSKEYID"
              "WORKSPACE_THUMBNAILS_SECRETACCESSKEY"
              "WORKSPACE_IMPORTS_ACCESSKEYID"
              "WORKSPACE_IMPORTS_SECRETACCESSKEY"
              ) "context" $ ) | nindent 12 }}
            {{- if .Values.workspaceApi.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if not .Values.workspaceApi.existingConfigMap }}
            - configMapRef:
                name: {{ template "carto.workspaceApi.fullname" . }}
            {{- end }}
            {{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "WORKSPACE_THUMBNAILS_ACCESSKEYID"
              "WORKSPACE_THUMBNAILS_SECRETACCESSKEY"
              "WORKSPACE_IMPORTS_ACCESSKEYID"
              "WORKSPACE_IMPORTS_SECRETACCESSKEY"
              ) "context" $ ) -}}
            {{- if $secretContent }}
            - secretRef:
                name: {{ include "carto.workspaceApi.secretName" . }}
            {{- end }}
        {{- if .Values.workspaceApi.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: workspace-api
          image: {{ template "carto.workspaceApi.image" . }}
          imagePullPolicy: {{ .Values.workspaceApi.image.pullPolicy }}
          {{- if .Values.workspaceApi.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.workspaceApi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.workspaceApi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.workspaceApi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.args "context" $) | nindent 12 }}
          {{ else }}
          args:
            - -ec
            - |
              npm run start:built
          {{- end }}
          env:
            - name: WORKSPACE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.postgresql.secretName" . }}
                  key: {{ include "carto.postgresql.secret.key" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carto.redis.secretName" . }}
                  key: {{ include "carto.redis.existingsecret.key" . | quote }}
            {{- include "carto._utils.generateSecretDefs" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "WORKSPACE_THUMBNAILS_ACCESSKEYID"
              "WORKSPACE_THUMBNAILS_SECRETACCESSKEY"
              "WORKSPACE_THUMBNAILS_STORAGE_ACCESSKEY"
              "WORKSPACE_IMPORTS_ACCESSKEYID"
              "WORKSPACE_IMPORTS_SECRETACCESSKEY"
              "WORKSPACE_IMPORTS_STORAGE_ACCESSKEY"
              ) "context" $ ) | nindent 12 }}
            {{- if .Values.workspaceApi.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if not .Values.workspaceApi.existingConfigMap }}
            - configMapRef:
                name: {{ template "carto.workspaceApi.fullname" . }}
            {{- end }}
            {{- if .Values.workspaceApi.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.workspaceApi.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- $secretContent := include "carto._utils.generateSecretObjects" (dict "vars" (list
              "ENCRYPTION_SECRET_KEY"
              "WORKSPACE_THUMBNAILS_ACCESSKEYID"
              "WORKSPACE_THUMBNAILS_SECRETACCESSKEY"
              "WORKSPACE_THUMBNAILS_STORAGE_ACCESSKEY"
              "WORKSPACE_IMPORTS_ACCESSKEYID"
              "WORKSPACE_IMPORTS_SECRETACCESSKEY"
              "WORKSPACE_IMPORTS_STORAGE_ACCESSKEY"
            ) "context" $ ) -}}
            {{- if $secretContent }}
            - secretRef:
                name: {{ include "carto.workspaceApi.secretName" . }}
            {{- end }}
          {{- if .Values.workspaceApi.resources }}
          resources: {{- toYaml .Values.workspaceApi.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.workspaceApi.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.workspaceApi.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.workspaceApi.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.workspaceApi.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.workspaceApi.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.workspaceApi.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- else if .Values.workspaceApi.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.workspaceApi.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.workspaceApi.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- else if .Values.workspaceApi.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.workspaceApi.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gcp-default-service-account-key
              mountPath: {{ include "carto.google.secretMountDir" . }}
              readOnly: true
            {{- if ( include "carto.gcpBucketsServiceAccountKey.used" . ) }}
            - name: gcp-buckets-service-account-key
              mountPath: {{ include "carto.gcpBucketsServiceAccountKey.secretMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
            - name: postgresql-ssl-ca
              mountPath: {{ include "carto.postgresql.configMapMountDir" . }}
              readOnly: true
            {{- end }}
            {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
            - name: redis-tls-ca
              mountPath: {{ include "carto.redis.configMapMountDir" . }}
              readOnly: true
            {{- end }}
          {{- if .Values.workspaceApi.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.workspaceApi.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.workspaceApi.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: gcp-default-service-account-key
          secret:
            secretName: {{ include "carto.google.secretName" . }}
            items:
              - key: {{ include "carto.google.secretKey" . }}
                path: {{ include "carto.google.secretMountFilename" . }}
        {{- if ( include "carto.gcpBucketsServiceAccountKey.used" . ) }}
        - name: gcp-buckets-service-account-key
          secret:
            secretName: {{ include "carto.gcpBucketsServiceAccountKey.secretName" . }}
            items:
              - key: {{ include "carto.gcpBucketsServiceAccountKey.secretKey" . }}
                path: {{ include "carto.gcpBucketsServiceAccountKey.secretMountFilename" . }}
        {{- end }}
        {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA }}
        - name: postgresql-ssl-ca
          configMap:
            name: {{ include "carto.postgresql.configMapName" . }}
        {{- end }}
        {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
        - name: redis-tls-ca
          configMap:
            name: {{ include "carto.redis.configMapName" . }}
        {{- end }}
        {{- if .Values.workspaceApi.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.workspaceApi.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
