{{- if not .Values.workspaceApi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.workspaceApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  ENCRYPTION_SECRET_KEY: {{ .Values.cartoSecrets.encryptionSecretKey.value | b64enc | quote }}
  {{- if eq .Values.customConfigValues.storageProvider "s3" }}
  WORKSPACE_THUMBNAILS_ACCESSKEYID: {{ .Values.appSecrets.awsAccessKeyId.value | b64enc | quote }}
  WORKSPACE_THUMBNAILS_SECRETACCESSKEY: {{ .Values.appSecrets.awsAccessKeySecret.value | b64enc | quote }}
  WORKSPACE_IMPORTS_ACCESSKEYID: {{ .Values.appSecrets.awsAccessKeyId.value | b64enc | quote }}
  WORKSPACE_IMPORTS_SECRETACCESSKEY: {{ .Values.appSecrets.awsAccessKeySecret.value | b64enc | quote }}
  {{- end }}
{{- end }}
