{{- if and (or .Values.sqlWorker.podDisruptionBudget.enabled .Values.highAvailability.enabled)}}
---
apiVersion: {{ .Values.global.kubernetesPolicyVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "carto.sqlWorker.fullname" . }}-pdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
spec:
{{- if .Values.sqlWorker.podDisruptionBudget.enabled }}
{{- if .Values.sqlWorker.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.sqlWorker.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.sqlWorker.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.sqlWorker.podDisruptionBudget.maxUnavailable }}
{{- end }}
{{- else }}
  maxUnavailable: 1
{{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: sql-worker
{{- end }}