apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.accountsApi.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: accounts-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  AUTH0_AUDIENCE: "275509697556054314@carto_frontend"
  ACCOUNTS_PORT: "{{ .Values.accountsApi.containerPorts.http }}"
  # ⬇️ change me
  ACCOUNTS_REACT_APP_CLIENT_ID: "275509697556054314@carto_frontend"
  # ⬇️ change me
  ACCOUNTS_AUTH0_CLIENT_ID: "275509697556054314@carto_frontend"
  
  ACCOUNTS_HONEYCOMB_UPLOAD_EVENTS: "true"
  ACCOUNTS_HONEYCOMB_DATASET: "mlopez-personal"
  # ACCOUNTS_HONEYCOMB_API_KEY: "not_setted"

  ACCOUNTS_BASE_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc"
  ACCOUNTS_VITE_BASE_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc"
  WORKSPACE_VITE_URL_TEMPLATE: "https://{{ .Values.appConfigValues.selfHostedDomain }}"
  ACCOUNTS_INVITE_URL_TEMPLATE: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc/account/invite?code={code}"
  ACCOUNTS_CARTO_DATAWAREHOUSE_ENABLED: "false"
  BOBSLED_EXPORT_STORAGE_BUCKET: "not_setted"
  AUTH0_NAMESPACE: "http://app.carto.com"
  ACCOUNTS_POSTGRES_HOST: {{ include "carto.postgresql.host" . }}
  ACCOUNTS_POSTGRES_SSL_ENABLED: "false"
  ACCOUNTS_POSTGRES_DB: "accounts"
  AUTH0_DOMAIN: "zitadel.mlr.carto.io"
  NODE_OPTIONS: "--max-old-space-size=768"
  PUBSUB_MODE: "pull"
  ACCOUNTS_ACTIVITY_DATA_BUCKET_NAME: "not_setted"
  EVENT_BUS_TOPIC: "event-bus-pub"
  ACCOUNTS_DO_PROJECT_ID: "carto-data-02-dev"
  PUBSUB_DATA_UPDATES_TOPICS_TEMPLATE: "data-updates-pub"

  ACCOUNTS_PAYMENTS_RECURLY_SUBDOMAIN: "carto-development"
  LOG_LEVEL: "debug"
  BOBSLED_ENVIRONMENT_NAME: "carto"

  PUBSUB_COMMON_ACCOUNTS_TOPIC: "commons-pub"
  PUBSUB_PROJECT_ID: "not_setted"
  ACCOUNTS_AUTH0_MANAGEMENT_AUDIENCE: "not_setted"
  ACCOUNTS_ERROR_RESPONSE_STACK_TRACE: "true"
  ACCOUNTS_CARTO_DATAWAREHOUSE_BILLING_ACCOUNT_NAME: "not_setted"
  GCLOUD_PROJECT: "not_setted"
  PUBSUB_DATA_UPDATES_ACCOUNTS_TOPIC: "data-updates-pub"

  RABBITMQ_CONNECTION_URL: amqp://guest:guest@{{ include "carto.rabbitMq.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:5672/

  ACCOUNTS_CARTO_DATAWAREHOUSE_ENVIRONMENT: "not_setted"
  ACCOUNTS_CARTO_DATAWAREHOUSE_FOLDER_ID: "not_setted"
  ACCOUNTS_CARTO_DATAWAREHOUSE_CUSTOMER_DATA: "false"


# export ACCOUNTS_POSTGRES_HOST=localhost
# export ACCOUNTS_POSTGRES_DB=accounts
# export ACCOUNTS_POSTGRES_USER=
# export ACCOUNTS_POSTGRES_PASSWORD=
# export ACCOUNTS_POSTGRES_PORT=5432
# export ACCOUNTS_POSTGRES_SSL_MODE=disable


### Secrets setted
  ACCOUNTS_INVITE_JWT_SECRET: "ajF0wiYg+KiJ"


### Secrets not setted
  ACCOUNTS_INCOMING_AUTH0_WEBHOOK_AUTH_USER: "not_setted"
  ACCOUNTS_PARTNER_CONNECT_SNOWFLAKE_PARTNER_SECRET: "not_setted"
  ACCOUNTS_INCOMING_AUTH0_WEBHOOK_AUTH_PASSWORD: "not_setted"
  ACCOUNTS_BACKOFFICE_AUTH_USER: "not_setted"
  ACCOUNTS_PAYMENTS_RECURLY_WEBHOOKS_AUTH_PASSWORD: "not_setted"
  ACCOUNTS_PAYMENTS_RECURLY_API_KEY: "not_setted"
  ACCOUNTS_PAYMENTS_RECURLY_WEBHOOKS_AUTH_USER: "not_setted"
  REPLICATED_API_SERVICE_ACCOUNT: "not_setted"
  BOBSLED_ACCOUNT_SECRET: "not_setted"

  BOBSLED_CLIENT_ID: "not_setted"
  ACCOUNTS_AUTH0_CLIENT_SECRET: "not_setted"
  ACCOUNTS_SENDGRID_API_KEY: "not_setted"

  BOBSLED_ACCOUNT_EMAIL: "not_setted"
  ACCOUNTS_BACKOFFICE_AUTH_PASSWORD: "not_setted"

  ACCOUNTS_ASK_NICELY_API_SECRET: "not_setted"
  ACCOUNTS_PARTNER_CONNECT_SNOWFLAKE_PARTNER_ID: "not_setted"


### Required by accounts-sub
  PUBSUB_DATA_UPDATES_ACCOUNTS_SUBSCRIPTION: "data-updates-account-sub"
  PUBSUB_COMMON_ACCOUNTS_SUBSCRIPTION: "commons-sub"
