{{- if .Values.internalRedis.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "carto.redis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: redis
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  minReplicas: {{ .Values.internalRedis.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.internalRedis.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "carto.redis.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.internalRedis.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}