{{- if and .Values.internalRedis.enabled (not .Values.internalRedis.existingSecret)}}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.redis.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: redis
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
    checksum/redis-password: {{ include "carto.redis.passwordChecksum" . }}
data:
  {{ include "carto.redis.existingsecret.key" . }}: {{ .Values.internalRedis.auth.password | b64enc }}
{{- end }}