{{- if not .Values.workspaceSubscriber.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.workspaceSubscriber.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-subscriber
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  .env: |
    # Common configuration
    # Fully qualified domain where CARTO will be accesible
    SELFHOSTED_DOMAIN={{ .Values.cartoConfigValues.selfHostedDomain }}
    # Configuration for PostgreSQL
    WORKSPACE_POSTGRES_HOST="{{ include "carto.postgresql.host" . }}"
    WORKSPACE_POSTGRES_PORT="{{ include "carto.postgresql.port" . }}"
    # Customer project and tenant name
    SELFHOSTED_TENANT_ID={{ .Values.cartoConfigValues.selfhostedTenantId }}
    SELFHOSTED_GCP_PROJECT_ID="carto-tnt-${SELFHOSTED_TENANT_ID}"
    # Change the following and read the documentation to use your own buckets
    WORKSPACE_THUMBNAILS_BUCKET="${SELFHOSTED_GCP_PROJECT_ID}-thumbnails-storage"
    WORKSPACE_IMPORTS_BUCKET="${SELFHOSTED_GCP_PROJECT_ID}-client-storage"
    IMPORT_BUCKET="${SELFHOSTED_GCP_PROJECT_ID}-import-storage"
    # Router
    ROUTER_SSL_AUTOGENERATE={{ .Values.cartoConfigValues.routerSslAutogenerate }}
    CARTO_AUTH0_CLIENT_ID={{ .Values.cartoConfigValues.cartoAuth0ClientId }}
    CARTO_AUTH0_CUSTOM_DOMAIN={{ .Values.cartoConfigValues.cartoAuth0CustomDomain }}
    ACC_DOMAIN={{ .Values.cartoConfigValues.cartoAccDomain }}
    ACC_GCP_PROJECT_ID={{ .Values.cartoConfigValues.cartoAccGcpProjectId }}
    ACC_GCP_PROJECT_REGION={{ .Values.cartoConfigValues.cartoAccGcpProjectRegion }}
    CARTO_SELFHOSTED_CARTO_DW_LOCATION={{ .Values.cartoConfigValues.cartoSelfhostedDwLocation }}
    GOOGLE_APPLICATION_CREDENTIALS="../certs/key.json"
    CARTO3_SELFHOSTED_VOLUMES_BASE_PATH="./"
    DOCKER_REGISTRY_BASE_PATH="gcr.io/carto-onprem-artifacts"
    CARTO_SELFHOSTED_AUTH0_CLIENT_ID="${CARTO_AUTH0_CLIENT_ID}"
    ### END VALUES FOR EACH ONPREM #########################
    ### GENERIC CONF
    ### WWW variables
    REACT_APP_CLIENT_ID="${CARTO_AUTH0_CLIENT_ID}"
    REACT_APP_AUTH0_DOMAIN="${CARTO_AUTH0_CUSTOM_DOMAIN}"
    REACT_APP_ACCOUNTS_API_URL="https://${ACC_DOMAIN}"
    REACT_APP_ACCOUNTS_URL="https://${SELFHOSTED_DOMAIN}/acc/"
    REACT_APP_WORKSPACE_API_URL="https://${SELFHOSTED_DOMAIN}/workspace-api"
    REACT_APP_API_BASE_URL="https://${SELFHOSTED_DOMAIN}/api"
    REACT_APP_PUBLIC_MAP_URL="https://${SELFHOSTED_DOMAIN}/api/v3/maps/public"
    REACT_APP_AUTH0_AUDIENCE="carto-cloud-native-api"
    REACT_APP_WORKSPACE_URL_TEMPLATE="https://{tenantDomain}"
    REACT_APP_CUSTOM_TENANT="${SELFHOSTED_TENANT_ID}"
    REACT_APP_HUBSPOT_ID="474999"
    REACT_APP_HUBSPOT_LIMIT_FORM_ID="cd9486fa-5766-4bac-81b9-d8c6cd029b3b"
    REACT_APP_BIGQUERY_OAUTH="false"
    ## Common config
    AUTH0_AUDIENCE="carto-cloud-native-api"
    AUTH0_DOMAIN="${CARTO_AUTH0_CUSTOM_DOMAIN}"
    AUTH0_NAMESPACE="http://app.carto.com"
    LOG_LEVEL="debug"
    REDIS_CACHE_PREFIX="onprem"
    REDIS_HOST="{{ include "carto.redis.host" . }}"
    REDIS_PORT="{{ include "carto.redis.port" . }}"
    ## PUB SUB
    PUBSUB_MODE="pull"
    PUBSUB_PROJECT_ID="${SELFHOSTED_GCP_PROJECT_ID}"
    ## Conflictive with onprem tenant && regular tenants
    PUBSUB_DATA_UPDATES_TOPICS_TEMPLATE="projects/{project_id}/topics/data-updates"
    EVENT_BUS_TOPIC="projects/${ACC_GCP_PROJECT_ID}/topics/${ACC_GCP_PROJECT_REGION}-event-bus"
    EVENT_BUS_PROJECT_ID="${ACC_GCP_PROJECT_ID}"
    DO_ENABLED="false"
    ## Workspace config
    CARTO_SELFHOSTED_NAME="${SELFHOSTED_TENANT_ID}"
    CARTO_SELFHOSTED_DOMAIN="${SELFHOSTED_DOMAIN}"
    CARTO_SELFHOSTED_GCP_PROJECT_ID="${SELFHOSTED_GCP_PROJECT_ID}"
    WORKSPACE_POSTGRES_USER="{{ include "carto.postgresql.user" . }}"
    WORKSPACE_POSTGRES_DB="{{ include "carto.postgresql.databaseName" . }}"
    WORKSPACE_PUBSUB_DATA_UPDATES_TOPIC="projects/${SELFHOSTED_GCP_PROJECT_ID}/topics/data-updates"
    WORKSPACE_PUBSUB_DATA_UPDATES_SUBSCRIPTION="projects/${SELFHOSTED_GCP_PROJECT_ID}/subscriptions/data-updates-workspace-sub"
    ## Maps API config
    MAPS_API_V3_RESOURCE_URL_HOST="${SELFHOSTED_DOMAIN}"
    MAPS_API_V3_RESOURCE_URL_ALLOWED_HOSTS="${SELFHOSTED_DOMAIN}"
    ## Import API config
    IMPORT_TENANT_ID="${SELFHOSTED_TENANT_ID}"
    IMPORT_WORKER_PROCESSING_DIR="/tmp/import-worker"
    IMPORT_PUBSUB_TENANT_BUS_TOPIC="projects/${SELFHOSTED_GCP_PROJECT_ID}/topics/tenant-bus"
    IMPORT_PUBSUB_TENANT_BUS_SUBSCRIPTION="projects/${SELFHOSTED_GCP_PROJECT_ID}/subscriptions/tenant-bus-import-sub"
{{- end }}
