{{- if not .Values.workspaceSubscriber.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.workspaceSubscriber.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-subscriber
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  AUTH0_AUDIENCE: "carto-cloud-native-api"
  AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  BIGQUERY_OAUTH2_CLIENT_ID: {{ .Values.appConfigValues.bigqueryOauth2ClientId | quote }}
  {{- if .Values.cartoConfigValues.featureFlagsOverrides }}
  CARTO_FEATURE_FLAGS_FILE_PATH: {{ include "carto.featureFlags.configMapMountDir" . | quote }}
  {{- end }}
  CARTO_SELFHOSTED_DOMAIN: {{ .Values.appConfigValues.selfHostedDomain | quote }}
  CARTO_SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  CARTO_SELFHOSTED_NAME: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  CARTO_SELFHOSTED_VERSION: {{ .Chart.AppVersion | quote }}
  {{- if .Values.replicated.enabled }}
  CARTO_SELFHOSTED_REPLICATED_SDK_DOMAIN: "replicated.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:3000"
  {{- end }}
  {{- if eq .Values.appConfigValues.logLevel "debug" }}
  CARTO_TRACING_MODE: "local"
  {{- end }}
  COMPUTE_PUBSUB_DATA_UPDATES_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/data-updates-compute-sub"
  EVENT_BUS_PROJECT_ID: {{ .Values.cartoConfigValues.cartoAccGcpProjectId | quote }}
  EVENT_BUS_TOPIC: "projects/{{ .Values.cartoConfigValues.cartoAccGcpProjectId }}/topics/{{ .Values.cartoConfigValues.cartoAccGcpProjectRegion }}-event-bus"
  {{- if not .Values.commonBackendServiceAccount.enableGCPWorkloadIdentity }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ include "carto.google.secretMountAbsolutePath" . }}
  {{- end }}
  NODE_OPTIONS: {{ template "carto.workspaceSubscriber.nodeOptions" . }}
  REDIS_CACHE_PREFIX: "onprem"
  REDIS_HOST: {{ include "carto.redis.host" . }}
  REDIS_PORT: {{ include "carto.redis.port" . }}
  REDIS_TLS_ENABLED: {{ .Values.externalRedis.tlsEnabled | quote }}
  {{- if and .Values.externalRedis.tlsEnabled .Values.externalRedis.tlsCA }}
  REDIS_TLS_CA: {{ include "carto.redis.configMapMountAbsolutePath" . }}
  {{- end }}
  LOG_LEVEL: {{ .Values.appConfigValues.logLevel | quote }}
  PUBSUB_DATA_UPDATES_TOPICS_TEMPLATE: "projects/{project_id}/topics/data-updates"
  PUBSUB_MODE: "pull"
  PUBSUB_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  PUBSUB_PROXY_HOST: {{ .Values.cartoConfigValues.pubsubHost | quote }}
  PUBSUB_USE_REST_API: {{ .Values.cartoConfigValues.usePubSubRestApi | quote }}
  SELFHOSTED_GCP_PROJECT_ID: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  WORKSPACE_ERROR_RESPONSE_STACK_TRACE: {{ .Values.cartoConfigValues.enableErrorResponseStackTrace | quote }}
  WORKSPACE_SYNC_DATA_ENABLED: "true"
  WORKSPACE_IMPORTS_BUCKET: {{ .Values.appConfigValues.workspaceImportsBucket | quote }}
  WORKSPACE_POSTGRES_DB: {{ include "carto.postgresql.databaseName" . }}
  WORKSPACE_POSTGRES_HOST: {{ include "carto.postgresql.host" . }}
  WORKSPACE_POSTGRES_PORT: {{ include "carto.postgresql.port" . }}
  WORKSPACE_POSTGRES_USER: {{ include "carto.postgresql.user" . }}
  WORKSPACE_POSTGRES_SSL_ENABLED: {{ .Values.externalPostgresql.sslEnabled | quote }}
  {{- if and .Values.externalPostgresql.sslEnabled .Values.externalPostgresql.sslCA  }}
  WORKSPACE_POSTGRES_SSL_CA: {{ include "carto.postgresql.configMapMountAbsolutePath" . }}
  {{- end }}
  {{- if .Values.externalPostgresql.awsEksPodIdentityEnabled }}
  CARTO_SELFHOSTED_AWS_RDS_METADATA_REGION: {{ .Values.externalPostgresql.awsRdsRegion | quote }}
  CARTO_SELFHOSTED_AWS_EKS_POD_IDENTITY_METADATA_DB_ENABLED: {{ .Values.externalPostgresql.awsEksPodIdentityEnabled | quote }}
  {{- end }}
  WORKSPACE_PUBSUB_DATA_UPDATES_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/data-updates-workspace-sub"
  WORKSPACE_PUBSUB_DATA_UPDATES_TOPIC: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/topics/data-updates"
  WORKSPACE_PUBSUB_EVENT_BUS_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/event-bus-workspace-sub"
  WORKSPACE_PUBSUB_TENANT_BUS_SUBSCRIPTION: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/subscriptions/tenant-bus-sub"
  WORKSPACE_NOTIFIER_PUBLISH_URL: "http://{{ include "carto.notifier.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.notifier.service.ports.internal }}/publish/"
  WORKSPACE_PUBSUB_TENANT_BUS_TOPIC: "projects/{{ .Values.cartoConfigValues.selfHostedGcpProjectId }}/topics/tenant-bus"
  WORKSPACE_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  WORKSPACE_THUMBNAILS_BUCKET: {{ .Values.appConfigValues.workspaceThumbnailsBucket | quote }}
  WORKSPACE_DO_PROJECT_ID: {{ .Values.cartoConfigValues.dataObservatoryProjectId | quote }}
  {{- if .Values.appConfigValues.workloadIdentityConnection.enabled }}
  WORKSPACE_WORKLOAD_IDENTITY_WORKFLOWS_TEMP: {{ .Values.appConfigValues.workloadIdentityConnection.workflowsTempLocation | quote }}
  WORKSPACE_WORKLOAD_IDENTITY_BILLING_PROJECT: {{ .Values.appConfigValues.workloadIdentityConnection.billingProject | quote }}
  WORKSPACE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT_EMAIL: {{ .Values.appConfigValues.workloadIdentityConnection.serviceAccountEmail | quote }}
  WORKSPACE_WORKLOAD_IDENTITY_CONNECTION_OWNER_ID: {{ .Values.appConfigValues.workloadIdentityConnection.connectionOwner | quote }}
  {{- end }}
  {{- if .Values.appConfigValues.defaultAtLocation.bigquery }}
  AT_LOCATION_BIGQUERY: {{ .Values.appConfigValues.defaultAtLocation.bigquery }}
  {{- end }}
  {{- if .Values.externalProxy.enabled }}
  HTTP_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  http_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  HTTPS_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  https_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  GRPC_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  grpc_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  NODE_TLS_REJECT_UNAUTHORIZED: {{ ternary "1" "0" .Values.externalProxy.sslRejectUnauthorized | quote }}
  {{- if gt (len .Values.externalProxy.excludedDomains) 0 }}
  NO_PROXY: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  no_proxy: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  {{- end }}
  {{- if or .Values.externalProxy.sslCA .Values.externalProxy.sslCAConfigmap.name }}
  NODE_EXTRA_CA_CERTS: {{ include "carto.proxy.configMapMountAbsolutePath" . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
