{{- if not .Values.workspaceWww.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.workspaceWww.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-www
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  CARTO_DATA_WAREHOUSE_ENABLED: {{ .Values.cartoConfigValues.cartoDataWarehouseEnabled | quote }}
  {{- if .Values.cartoConfigValues.featureFlagsOverrides }}
  CARTO_FEATURE_FLAGS_FILE_PATH: {{ include "carto.featureFlags.configMapMountDir" . | quote }}
  {{- end }}
  {{- if $.Values.appConfigValues.bigqueryOauth2ClientId }}
  REACT_APP_BIGQUERY_OAUTH: "true"
  {{- else }}
  REACT_APP_BIGQUERY_OAUTH: "false"
  {{- end }}
  CARTO_SELFHOSTED_VERSION: {{ .Chart.AppVersion | quote }}
  LOG_LEVEL: {{ .Values.appConfigValues.logLevel | quote }}
  REACT_APP_ACCOUNTS_API_URL: "https://{{ .Values.cartoConfigValues.cartoAccApiDomain }}"
  REACT_APP_ACCOUNTS_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc/"
  REACT_APP_AI_API_URL: "https://{{ .Values.cartoConfigValues.cartoAccApiDomain }}/ai-api"
  REACT_APP_API_BASE_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/api"
  REACT_APP_AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  REACT_APP_CLIENT_ID: {{ .Values.cartoConfigValues.cartoAuth0ClientId | quote }}
  REACT_APP_DO_API_URL: "https://{{ .Values.cartoConfigValues.cartoDoApiDomain }}"
  REACT_APP_DO_ASSETS_URL: "https://{{ .Values.cartoConfigValues.cartoDoAssetsDomain }}"
  REACT_APP_HUBSPOT_ID: "474999"
  REACT_APP_HUBSPOT_LIMIT_FORM_ID: "cd9486fa-5766-4bac-81b9-d8c6cd029b3b"
  REACT_APP_HUBSPOT_REQUEST_SUBSCRIPTION_FORM_ID: "49d53632-80f9-4720-b4be-bf623a527af4"
  REACT_APP_LAUNCH_DARKLY_CLIENT_SIDE_ID: {{ .Values.cartoConfigValues.launchDarklyClientSideId | quote }}
  REACT_APP_PUBLIC_MAP_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/api/v3/maps/public"
  REACT_APP_WORKSPACE_API_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/workspace-api"
  REACT_APP_NOTIFIER_API_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/notifier"
  REACT_APP_WORKSPACE_URL_TEMPLATE: "https://{tenantDomain}"
  THUMBNAILS_BUCKET_EXTERNAL_URL: {{ .Values.appConfigValues.thumbnailsBucketExternalURL | quote }}
  REACT_APP_WORKSPACE_WWW_ENABLE_TRACKJS: {{ .Values.appConfigValues.enableTrackJS | quote }}
  REACT_APP_WORKSPACE_WWW_ENABLE_EXPORTS: "false"
  REACT_APP_WORKSPACE_WWW_ENABLE_GENAI: "false"
  WAREHOUSE_PROVIDERS_SNOWFLAKE: "true"
  WAREHOUSE_PROVIDERS_BIGQUERY: "true"
  WAREHOUSE_PROVIDERS_POSTGRES: "true"
  WAREHOUSE_PROVIDERS_REDSHIFT: "true"
  WAREHOUSE_PROVIDERS_DATABRICKS: "true"
  WAREHOUSE_PROVIDERS_DATABRICKS_REST: "true"
  WAREHOUSE_PROVIDERS_FABRIC: "true"
  {{- if .Values.appConfigValues.ssoOrganizationId }}
  REACT_APP_ORGANIZATION_ID: {{ .Values.appConfigValues.ssoOrganizationId }}
  {{- end }}
{{- end }}
