{{- if not .Values.workspaceWww.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.workspaceWww.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: workspace-www
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if $.Values.appConfigValues.bigqueryOauth2ClientId }}
  VITE_BIGQUERY_OAUTH: "true"
  {{- else }}
  VITE_BIGQUERY_OAUTH: "false"
  {{- end }}
  CARTO_SELFHOSTED_VERSION: {{ .Chart.AppVersion | quote }}
  LOG_LEVEL: "debug"
  VITE_ACCOUNTS_API_URL: "https://{{ .Values.cartoConfigValues.cartoAccApiDomain }}"
  VITE_ACCOUNTS_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/acc/"
  VITE_API_BASE_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/api"
  VITE_AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  VITE_CLIENT_ID: {{ .Values.cartoConfigValues.cartoAuth0ClientId | quote }}
  VITE_HUBSPOT_ID: "474999"
  VITE_HUBSPOT_LIMIT_FORM_ID: "cd9486fa-5766-4bac-81b9-d8c6cd029b3b"
  VITE_HUBSPOT_REQUEST_SUBSCRIPTION_FORM_ID: "49d53632-80f9-4720-b4be-bf623a527af4"
  VITE_LAUNCH_DARKLY_CLIENT_SIDE_ID: {{ .Values.cartoConfigValues.launchDarklyClientSideId | quote }}
  VITE_PUBLIC_MAP_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/api/v3/maps/public"
  VITE_WORKSPACE_API_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/workspace-api"
  VITE_NOTIFIER_API_URL: "https://{{ .Values.appConfigValues.selfHostedDomain }}/notifier"
  VITE_WORKSPACE_URL_TEMPLATE: "https://{tenantDomain}"
  THUMBNAILS_BUCKET_EXTERNAL_URL: {{ .Values.appConfigValues.thumbnailsBucketExternalURL | quote }}
  VITE_WORKSPACE_WWW_ENABLE_TRACKJS: {{ .Values.appConfigValues.enableTrackJS | quote }}
  VITE_WORKSPACE_WWW_ENABLE_EXPORTS: "false"
  VITE_ASKNICELY_MIN_HOURS_ACCOUNT_OLD_ENOUGH: "1920"
{{- end }}
