{{- if not .Values.workspaceWww.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carto.workspaceWww.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: trivy
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  # Common configuration
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonSecretConfiguration "context" $ ) | nindent 2 }}
  # workspace-www configuration
  {{- include "common.tplvalues.render" ( dict "value" .Values.workspaceWww.secretConfiguration "context" $ ) | nindent 2 }}
{{- end }}
