cartoConfigValues:
  selfHostedDomain: "carto3-selfhosted.lan"
  selfHostedTenantId: "onp-ahg-k8s-helm"
  selfHostedGcpProjectId: "carto-tnt-onp-ahg-k8s-helm"
  cartoAuth0ClientId: "CiIpQbeb6oRiVTOwlGaz0P1rjb1a1PU3"
  cartoAuth0CustomDomain: "auth.stag.carto.com"
  cartoAccDomain: "accounts.stag.app.carto.com"
  cartoAccGcpProjectId: "carto-acc-us-east1-1-stag"
  cartoAccGcpProjectRegion: "us-east1-1-stag"
  cartoSelfhostedDwLocation: "US"
  workspaceThumbnailsBucket: "carto-tnt-onp-ahg-k8s-helm-thumbnails-storage"
  workspaceImportsBucket: "carto-tnt-onp-ahg-k8s-helm-client-storage"
  importBucket: "carto-tnt-onp-ahg-k8s-helm-import-storage"
  routerSslAutogenerate: "0"
