name: Release - Autotag
on:
  push:
    branches:
      - main
    paths:
      - "chart/Chart.yaml"
jobs:
  create-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: Retrieve Release Version
        id: info
        shell: bash
        run: |
          set -eu
          echo "carto-release-version=$(yq .appVersion chart/Chart.yaml)" >> ${GITHUB_OUTPUT}
          echo "chart-release-version=$(yq .version chart/Chart.yaml)" >> ${GITHUB_OUTPUT}

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.X_GITHUB_CARTOFANTE }}
          commit: ${{ github.sha }}
          name: ${{ steps.info.outputs.chart-release-version }}
          tag: ${{ steps.info.outputs.chart-release-version }}
          prerelease: true
          body: "Release notes for this version are available at https://docs.carto.com/get-help/deployment-options/self-hosted/release-notes#${{ steps.info.outputs.carto-release-version }}"
