name: "Create OnPrem Release"
on:
  push:
    branches:
      - main
env:
  GCLOUD_VERSION: '297.0.1' # https://github.com/google-github-actions/setup-gcloud/issues/128
  CHARTS_REPOSITORY: "https://carto-selfhosted-charts.storage.googleapis.com/"
  CHARTS_BUCKET: "gs://carto-selfhosted-charts"
  BASE_BRANCH_HELM: "main"
  PROJECT_ID: carto-onprem-artifacts
  ARTIFACTS_PROJECT_ID: "carto-artifacts"

jobs:
  helm-package:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.CARTO_ARTIFACTS_SERVICE_ACCOUNT }}
          project_id: ${{ env.ARTIFACTS_PROJECT_ID }}
      - name: Google Cloud install
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: ${{ env.GCLOUD_VERSION }}
      - name: Install helm
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Create package
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        shell: bash
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build chart
          helm package chart
          gsutil cp -r "${CHARTS_BUCKET}" .
          mkdir carto3-selfhosted-charts
          mv carto-selfhosted-charts/*.tgz carto3-selfhosted-charts/
          mv "carto-${RELEASE_CHART_VERSION}.tgz" carto3-selfhosted-charts/
          helm repo index carto3-selfhosted-charts --url "${CHARTS_REPOSITORY}"
      - name: Upload chart
        if: startsWith(github.event.head_commit.message, 'Self Hosted automated version bump')
        shell: bash
        run: |
          gsutil rsync -d carto3-selfhosted-charts/ "${CHARTS_BUCKET}"
