name: Renovate Dependencies
on:
  push:

  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.0
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: ".github/renovate-config.json"
          token: ${{ secrets.X_GITHUB_CARTOFANTE }}
