name: Renovate Dependencies
on:
  push:

  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.0
        with:
          configurationFile: ".github/renovate-config.json"
          token: ${{ secrets.X_GITHUB_CARTOFANTE }}
