name: "Create CARTO SelfHosted official release"
on:
  push

jobs:
  helm-package:
    timeout-minutes: 3
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Obtain release info
        id: release-info
        run: |
          if [ "prereleased" == "prereleased" ]; then
            yq -i '.version = .version + "-beta"' chart/Chart.yaml
            yq -i '.spec.chart.chartVersion = .spec.chart.chartVersion + "-beta"' manifests/kots-helm.yaml
            echo "channel-name=Release candidates" >> "$GITHUB_OUTPUT"
            echo "version=$(yq .version -r chart/Chart.yaml)" >> "$GITHUB_OUTPUT"
          else
            echo "channel-name=mcalzado replicated" >> "$GITHUB_OUTPUT"
            echo "version=$(yq .version -r chart/Chart.yaml)" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish release
        uses: ./.github/actions/publish-release
        with:
          replicated-channel: ${{ steps.release-info.outputs.channel-name }}
          version: ${{ steps.release-info.outputs.version }}
          release-notes: "CARTO Self-Hosted ${{ steps.release-info.outputs.version }}"
          trigger-action: "prereleased"
          gcloud-service-account: ${{ secrets.CARTO_ARTIFACTS_SERVICE_ACCOUNT }}
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
