name: 'vib'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-validate: # make sure chart is linted/safe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: vmware-labs/vmware-image-builder-action@main

  vib-k8s-verify: # verify in multiple target platforms
    runs-on: ubuntu-latest
    environment: vmware-image-builder
    needs: [vib-validate]
    strategy:
      matrix:
       include:
         - target-platform: gke
           target-platform-id: 91d398a2-25c4-4cda-8732-75a3cfc179a1
      fail-fast: false
    name: K8s verify ${{ matrix.target-platform}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: vmware-labs/vmware-image-builder-action@main
        with:
          pipeline: vib-platform-verify.json
        env:
          VIB_ENV_TARGET_PLATFORM: ${{ matrix.target-platform-id }}
          VIB_ENV_CARTO_RUNTIME_PARAMETERS: ${{ secrets.CARTO_RUNTIME_PARAMETERS }}
